{{- if include "qm.hasSecretEnv" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qm.fullname" . }}-env
  labels:
    {{- include "qm.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secretEnv }}
  {{- if $v }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
  {{- if and (not .Values.secretEnv.OIDC_CLIENT_ID) .Values.secretEnv.AUTH_CLIENT_ID }}
  OIDC_CLIENT_ID: {{ .Values.secretEnv.AUTH_CLIENT_ID | quote }}
  {{- end }}
  {{- if and (not .Values.secretEnv.OIDC_CLIENT_SECRET) .Values.secretEnv.AUTH_CLIENT_SECRET }}
  OIDC_CLIENT_SECRET: {{ .Values.secretEnv.AUTH_CLIENT_SECRET | quote }}
  {{- end }}
  {{- if and (not .Values.secretEnv.OIDC_ALLOWED_EMAILS) .Values.secretEnv.AUTH_ALLOWED_EMAILS }}
  OIDC_ALLOWED_EMAILS: {{ .Values.secretEnv.AUTH_ALLOWED_EMAILS | quote }}
  {{- end }}
{{- end }}
