{{- $root := . -}}
{{- range $name, $svc := .Values.services }}
{{- if and $svc.enabled (ne $name "admin") (ne $name "auth") }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "qm.fullname" $root }}-{{ $name }}
  labels:
    {{- include "qm.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  type: {{ $svc.serviceType | default "ClusterIP" }}
  selector:
    {{- include "qm.selectorLabels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
  ports:
    - name: http
      port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
{{- end }}
{{- end }}
