export interface EmojiRow {
  n: string;
  c: string;
  g: string;
  a?: string[];
}

export const EMOJI_GROUPS: readonly string[] = [
  "Smileys & Emotion",
  "People & Body",
  "Animals & Nature",
  "Food & Drink",
  "Travel & Places",
  "Activities",
  "Objects",
  "Symbols",
  "Flags",
];

export const EMOJI_ROWS: readonly EmojiRow[] = [
  { n: "grinning", c: "😀", g: "Smileys & Emotion" },
  { n: "smiley", c: "😃", g: "Smileys & Emotion" },
  { n: "smile", c: "😄", g: "Smileys & Emotion" },
  { n: "grin", c: "😁", g: "Smileys & Emotion" },
  { n: "laughing", c: "😆", g: "Smileys & Emotion", a: ["satisfied"] },
  { n: "sweat_smile", c: "😅", g: "Smileys & Emotion" },
  { n: "rolling_on_the_floor_laughing", c: "🤣", g: "Smileys & Emotion" },
  { n: "joy", c: "😂", g: "Smileys & Emotion" },
  { n: "slightly_smiling_face", c: "🙂", g: "Smileys & Emotion" },
  { n: "upside_down_face", c: "🙃", g: "Smileys & Emotion" },
  { n: "melting_face", c: "🫠", g: "Smileys & Emotion" },
  { n: "wink", c: "😉", g: "Smileys & Emotion" },
  { n: "blush", c: "😊", g: "Smileys & Emotion" },
  { n: "innocent", c: "😇", g: "Smileys & Emotion" },
  { n: "smiling_face_with_3_hearts", c: "🥰", g: "Smileys & Emotion" },
  { n: "heart_eyes", c: "😍", g: "Smileys & Emotion" },
  { n: "star-struck", c: "🤩", g: "Smileys & Emotion", a: ["grinning_face_with_star_eyes"] },
  { n: "kissing_heart", c: "😘", g: "Smileys & Emotion" },
  { n: "kissing", c: "😗", g: "Smileys & Emotion" },
  { n: "relaxed", c: "☺️", g: "Smileys & Emotion" },
  { n: "kissing_closed_eyes", c: "😚", g: "Smileys & Emotion" },
  { n: "kissing_smiling_eyes", c: "😙", g: "Smileys & Emotion" },
  { n: "smiling_face_with_tear", c: "🥲", g: "Smileys & Emotion" },
  { n: "yum", c: "😋", g: "Smileys & Emotion" },
  { n: "stuck_out_tongue", c: "😛", g: "Smileys & Emotion" },
  { n: "stuck_out_tongue_winking_eye", c: "😜", g: "Smileys & Emotion" },
  { n: "zany_face", c: "🤪", g: "Smileys & Emotion", a: ["grinning_face_with_one_large_and_one_small_eye"] },
  { n: "stuck_out_tongue_closed_eyes", c: "😝", g: "Smileys & Emotion" },
  { n: "money_mouth_face", c: "🤑", g: "Smileys & Emotion" },
  { n: "hugging_face", c: "🤗", g: "Smileys & Emotion" },
  {
    n: "face_with_hand_over_mouth",
    c: "🤭",
    g: "Smileys & Emotion",
    a: ["smiling_face_with_smiling_eyes_and_hand_covering_mouth"],
  },
  { n: "face_with_open_eyes_and_hand_over_mouth", c: "🫢", g: "Smileys & Emotion" },
  { n: "face_with_peeking_eye", c: "🫣", g: "Smileys & Emotion" },
  { n: "shushing_face", c: "🤫", g: "Smileys & Emotion", a: ["face_with_finger_covering_closed_lips"] },
  { n: "thinking_face", c: "🤔", g: "Smileys & Emotion" },
  { n: "saluting_face", c: "🫡", g: "Smileys & Emotion" },
  { n: "zipper_mouth_face", c: "🤐", g: "Smileys & Emotion" },
  { n: "face_with_raised_eyebrow", c: "🤨", g: "Smileys & Emotion", a: ["face_with_one_eyebrow_raised"] },
  { n: "neutral_face", c: "😐", g: "Smileys & Emotion" },
  { n: "expressionless", c: "😑", g: "Smileys & Emotion" },
  { n: "no_mouth", c: "😶", g: "Smileys & Emotion" },
  { n: "dotted_line_face", c: "🫥", g: "Smileys & Emotion" },
  { n: "face_in_clouds", c: "😶‍🌫️", g: "Smileys & Emotion" },
  { n: "smirk", c: "😏", g: "Smileys & Emotion" },
  { n: "unamused", c: "😒", g: "Smileys & Emotion" },
  { n: "face_with_rolling_eyes", c: "🙄", g: "Smileys & Emotion" },
  { n: "grimacing", c: "😬", g: "Smileys & Emotion" },
  { n: "face_exhaling", c: "😮‍💨", g: "Smileys & Emotion" },
  { n: "lying_face", c: "🤥", g: "Smileys & Emotion" },
  { n: "shaking_face", c: "🫨", g: "Smileys & Emotion" },
  { n: "head_shaking_horizontally", c: "🙂‍↔️", g: "Smileys & Emotion" },
  { n: "head_shaking_vertically", c: "🙂‍↕️", g: "Smileys & Emotion" },
  { n: "relieved", c: "😌", g: "Smileys & Emotion" },
  { n: "pensive", c: "😔", g: "Smileys & Emotion" },
  { n: "sleepy", c: "😪", g: "Smileys & Emotion" },
  { n: "drooling_face", c: "🤤", g: "Smileys & Emotion" },
  { n: "sleeping", c: "😴", g: "Smileys & Emotion" },
  { n: "face_with_bags_under_eyes", c: "🫩", g: "Smileys & Emotion" },
  { n: "mask", c: "😷", g: "Smileys & Emotion" },
  { n: "face_with_thermometer", c: "🤒", g: "Smileys & Emotion" },
  { n: "face_with_head_bandage", c: "🤕", g: "Smileys & Emotion" },
  { n: "nauseated_face", c: "🤢", g: "Smileys & Emotion" },
  { n: "face_vomiting", c: "🤮", g: "Smileys & Emotion", a: ["face_with_open_mouth_vomiting"] },
  { n: "sneezing_face", c: "🤧", g: "Smileys & Emotion" },
  { n: "hot_face", c: "🥵", g: "Smileys & Emotion" },
  { n: "cold_face", c: "🥶", g: "Smileys & Emotion" },
  { n: "woozy_face", c: "🥴", g: "Smileys & Emotion" },
  { n: "dizzy_face", c: "😵", g: "Smileys & Emotion" },
  { n: "face_with_spiral_eyes", c: "😵‍💫", g: "Smileys & Emotion" },
  { n: "exploding_head", c: "🤯", g: "Smileys & Emotion", a: ["shocked_face_with_exploding_head"] },
  { n: "face_with_cowboy_hat", c: "🤠", g: "Smileys & Emotion" },
  { n: "partying_face", c: "🥳", g: "Smileys & Emotion" },
  { n: "disguised_face", c: "🥸", g: "Smileys & Emotion" },
  { n: "sunglasses", c: "😎", g: "Smileys & Emotion" },
  { n: "nerd_face", c: "🤓", g: "Smileys & Emotion" },
  { n: "face_with_monocle", c: "🧐", g: "Smileys & Emotion" },
  { n: "confused", c: "😕", g: "Smileys & Emotion" },
  { n: "face_with_diagonal_mouth", c: "🫤", g: "Smileys & Emotion" },
  { n: "worried", c: "😟", g: "Smileys & Emotion" },
  { n: "slightly_frowning_face", c: "🙁", g: "Smileys & Emotion" },
  { n: "white_frowning_face", c: "☹️", g: "Smileys & Emotion" },
  { n: "open_mouth", c: "😮", g: "Smileys & Emotion" },
  { n: "hushed", c: "😯", g: "Smileys & Emotion" },
  { n: "astonished", c: "😲", g: "Smileys & Emotion" },
  { n: "flushed", c: "😳", g: "Smileys & Emotion" },
  { n: "pleading_face", c: "🥺", g: "Smileys & Emotion" },
  { n: "face_holding_back_tears", c: "🥹", g: "Smileys & Emotion" },
  { n: "frowning", c: "😦", g: "Smileys & Emotion" },
  { n: "anguished", c: "😧", g: "Smileys & Emotion" },
  { n: "fearful", c: "😨", g: "Smileys & Emotion" },
  { n: "cold_sweat", c: "😰", g: "Smileys & Emotion" },
  { n: "disappointed_relieved", c: "😥", g: "Smileys & Emotion" },
  { n: "cry", c: "😢", g: "Smileys & Emotion" },
  { n: "sob", c: "😭", g: "Smileys & Emotion" },
  { n: "scream", c: "😱", g: "Smileys & Emotion" },
  { n: "confounded", c: "😖", g: "Smileys & Emotion" },
  { n: "persevere", c: "😣", g: "Smileys & Emotion" },
  { n: "disappointed", c: "😞", g: "Smileys & Emotion" },
  { n: "sweat", c: "😓", g: "Smileys & Emotion" },
  { n: "weary", c: "😩", g: "Smileys & Emotion" },
  { n: "tired_face", c: "😫", g: "Smileys & Emotion" },
  { n: "yawning_face", c: "🥱", g: "Smileys & Emotion" },
  { n: "triumph", c: "😤", g: "Smileys & Emotion" },
  { n: "rage", c: "😡", g: "Smileys & Emotion" },
  { n: "angry", c: "😠", g: "Smileys & Emotion" },
  { n: "face_with_symbols_on_mouth", c: "🤬", g: "Smileys & Emotion", a: ["serious_face_with_symbols_covering_mouth"] },
  { n: "smiling_imp", c: "😈", g: "Smileys & Emotion" },
  { n: "imp", c: "👿", g: "Smileys & Emotion" },
  { n: "skull", c: "💀", g: "Smileys & Emotion" },
  { n: "skull_and_crossbones", c: "☠️", g: "Smileys & Emotion" },
  { n: "hankey", c: "💩", g: "Smileys & Emotion", a: ["poop", "shit"] },
  { n: "clown_face", c: "🤡", g: "Smileys & Emotion" },
  { n: "japanese_ogre", c: "👹", g: "Smileys & Emotion" },
  { n: "japanese_goblin", c: "👺", g: "Smileys & Emotion" },
  { n: "ghost", c: "👻", g: "Smileys & Emotion" },
  { n: "alien", c: "👽", g: "Smileys & Emotion" },
  { n: "space_invader", c: "👾", g: "Smileys & Emotion" },
  { n: "robot_face", c: "🤖", g: "Smileys & Emotion" },
  { n: "smiley_cat", c: "😺", g: "Smileys & Emotion" },
  { n: "smile_cat", c: "😸", g: "Smileys & Emotion" },
  { n: "joy_cat", c: "😹", g: "Smileys & Emotion" },
  { n: "heart_eyes_cat", c: "😻", g: "Smileys & Emotion" },
  { n: "smirk_cat", c: "😼", g: "Smileys & Emotion" },
  { n: "kissing_cat", c: "😽", g: "Smileys & Emotion" },
  { n: "scream_cat", c: "🙀", g: "Smileys & Emotion" },
  { n: "crying_cat_face", c: "😿", g: "Smileys & Emotion" },
  { n: "pouting_cat", c: "😾", g: "Smileys & Emotion" },
  { n: "see_no_evil", c: "🙈", g: "Smileys & Emotion" },
  { n: "hear_no_evil", c: "🙉", g: "Smileys & Emotion" },
  { n: "speak_no_evil", c: "🙊", g: "Smileys & Emotion" },
  { n: "love_letter", c: "💌", g: "Smileys & Emotion" },
  { n: "cupid", c: "💘", g: "Smileys & Emotion" },
  { n: "gift_heart", c: "💝", g: "Smileys & Emotion" },
  { n: "sparkling_heart", c: "💖", g: "Smileys & Emotion" },
  { n: "heartpulse", c: "💗", g: "Smileys & Emotion" },
  { n: "heartbeat", c: "💓", g: "Smileys & Emotion" },
  { n: "revolving_hearts", c: "💞", g: "Smileys & Emotion" },
  { n: "two_hearts", c: "💕", g: "Smileys & Emotion" },
  { n: "heart_decoration", c: "💟", g: "Smileys & Emotion" },
  { n: "heavy_heart_exclamation_mark_ornament", c: "❣️", g: "Smileys & Emotion" },
  { n: "broken_heart", c: "💔", g: "Smileys & Emotion" },
  { n: "heart_on_fire", c: "❤️‍🔥", g: "Smileys & Emotion" },
  { n: "mending_heart", c: "❤️‍🩹", g: "Smileys & Emotion" },
  { n: "heart", c: "❤️", g: "Smileys & Emotion" },
  { n: "pink_heart", c: "🩷", g: "Smileys & Emotion" },
  { n: "orange_heart", c: "🧡", g: "Smileys & Emotion" },
  { n: "yellow_heart", c: "💛", g: "Smileys & Emotion" },
  { n: "green_heart", c: "💚", g: "Smileys & Emotion" },
  { n: "blue_heart", c: "💙", g: "Smileys & Emotion" },
  { n: "light_blue_heart", c: "🩵", g: "Smileys & Emotion" },
  { n: "purple_heart", c: "💜", g: "Smileys & Emotion" },
  { n: "brown_heart", c: "🤎", g: "Smileys & Emotion" },
  { n: "black_heart", c: "🖤", g: "Smileys & Emotion" },
  { n: "grey_heart", c: "🩶", g: "Smileys & Emotion" },
  { n: "white_heart", c: "🤍", g: "Smileys & Emotion" },
  { n: "kiss", c: "💋", g: "Smileys & Emotion" },
  { n: "100", c: "💯", g: "Smileys & Emotion" },
  { n: "anger", c: "💢", g: "Smileys & Emotion" },
  { n: "boom", c: "💥", g: "Smileys & Emotion", a: ["collision"] },
  { n: "dizzy", c: "💫", g: "Smileys & Emotion" },
  { n: "sweat_drops", c: "💦", g: "Smileys & Emotion" },
  { n: "dash", c: "💨", g: "Smileys & Emotion" },
  { n: "hole", c: "🕳️", g: "Smileys & Emotion" },
  { n: "speech_balloon", c: "💬", g: "Smileys & Emotion" },
  { n: "eye-in-speech-bubble", c: "👁️‍🗨️", g: "Smileys & Emotion" },
  { n: "left_speech_bubble", c: "🗨️", g: "Smileys & Emotion" },
  { n: "right_anger_bubble", c: "🗯️", g: "Smileys & Emotion" },
  { n: "thought_balloon", c: "💭", g: "Smileys & Emotion" },
  { n: "zzz", c: "💤", g: "Smileys & Emotion" },
  { n: "wave", c: "👋", g: "People & Body" },
  { n: "raised_back_of_hand", c: "🤚", g: "People & Body" },
  { n: "raised_hand_with_fingers_splayed", c: "🖐️", g: "People & Body" },
  { n: "hand", c: "✋", g: "People & Body", a: ["raised_hand"] },
  { n: "spock-hand", c: "🖖", g: "People & Body" },
  { n: "rightwards_hand", c: "🫱", g: "People & Body" },
  { n: "leftwards_hand", c: "🫲", g: "People & Body" },
  { n: "palm_down_hand", c: "🫳", g: "People & Body" },
  { n: "palm_up_hand", c: "🫴", g: "People & Body" },
  { n: "leftwards_pushing_hand", c: "🫷", g: "People & Body" },
  { n: "rightwards_pushing_hand", c: "🫸", g: "People & Body" },
  { n: "ok_hand", c: "👌", g: "People & Body" },
  { n: "pinched_fingers", c: "🤌", g: "People & Body" },
  { n: "pinching_hand", c: "🤏", g: "People & Body" },
  { n: "v", c: "✌️", g: "People & Body" },
  { n: "crossed_fingers", c: "🤞", g: "People & Body", a: ["hand_with_index_and_middle_fingers_crossed"] },
  { n: "hand_with_index_finger_and_thumb_crossed", c: "🫰", g: "People & Body" },
  { n: "i_love_you_hand_sign", c: "🤟", g: "People & Body" },
  { n: "the_horns", c: "🤘", g: "People & Body", a: ["sign_of_the_horns"] },
  { n: "call_me_hand", c: "🤙", g: "People & Body" },
  { n: "point_left", c: "👈", g: "People & Body" },
  { n: "point_right", c: "👉", g: "People & Body" },
  { n: "point_up_2", c: "👆", g: "People & Body" },
  { n: "middle_finger", c: "🖕", g: "People & Body", a: ["reversed_hand_with_middle_finger_extended"] },
  { n: "point_down", c: "👇", g: "People & Body" },
  { n: "point_up", c: "☝️", g: "People & Body" },
  { n: "index_pointing_at_the_viewer", c: "🫵", g: "People & Body" },
  { n: "+1", c: "👍", g: "People & Body", a: ["thumbsup"] },
  { n: "-1", c: "👎", g: "People & Body", a: ["thumbsdown"] },
  { n: "fist", c: "✊", g: "People & Body" },
  { n: "facepunch", c: "👊", g: "People & Body", a: ["punch"] },
  { n: "left-facing_fist", c: "🤛", g: "People & Body" },
  { n: "right-facing_fist", c: "🤜", g: "People & Body" },
  { n: "clap", c: "👏", g: "People & Body" },
  { n: "raised_hands", c: "🙌", g: "People & Body" },
  { n: "heart_hands", c: "🫶", g: "People & Body" },
  { n: "open_hands", c: "👐", g: "People & Body" },
  { n: "palms_up_together", c: "🤲", g: "People & Body" },
  { n: "handshake", c: "🤝", g: "People & Body" },
  { n: "pray", c: "🙏", g: "People & Body" },
  { n: "writing_hand", c: "✍️", g: "People & Body" },
  { n: "nail_care", c: "💅", g: "People & Body" },
  { n: "selfie", c: "🤳", g: "People & Body" },
  { n: "muscle", c: "💪", g: "People & Body" },
  { n: "mechanical_arm", c: "🦾", g: "People & Body" },
  { n: "mechanical_leg", c: "🦿", g: "People & Body" },
  { n: "leg", c: "🦵", g: "People & Body" },
  { n: "foot", c: "🦶", g: "People & Body" },
  { n: "ear", c: "👂", g: "People & Body" },
  { n: "ear_with_hearing_aid", c: "🦻", g: "People & Body" },
  { n: "nose", c: "👃", g: "People & Body" },
  { n: "brain", c: "🧠", g: "People & Body" },
  { n: "anatomical_heart", c: "🫀", g: "People & Body" },
  { n: "lungs", c: "🫁", g: "People & Body" },
  { n: "tooth", c: "🦷", g: "People & Body" },
  { n: "bone", c: "🦴", g: "People & Body" },
  { n: "eyes", c: "👀", g: "People & Body" },
  { n: "eye", c: "👁️", g: "People & Body" },
  { n: "tongue", c: "👅", g: "People & Body" },
  { n: "lips", c: "👄", g: "People & Body" },
  { n: "biting_lip", c: "🫦", g: "People & Body" },
  { n: "baby", c: "👶", g: "People & Body" },
  { n: "child", c: "🧒", g: "People & Body" },
  { n: "boy", c: "👦", g: "People & Body" },
  { n: "girl", c: "👧", g: "People & Body" },
  { n: "adult", c: "🧑", g: "People & Body" },
  { n: "person_with_blond_hair", c: "👱", g: "People & Body" },
  { n: "man", c: "👨", g: "People & Body" },
  { n: "bearded_person", c: "🧔", g: "People & Body" },
  { n: "man_with_beard", c: "🧔‍♂️", g: "People & Body" },
  { n: "woman_with_beard", c: "🧔‍♀️", g: "People & Body" },
  { n: "red_haired_man", c: "👨‍🦰", g: "People & Body" },
  { n: "curly_haired_man", c: "👨‍🦱", g: "People & Body" },
  { n: "white_haired_man", c: "👨‍🦳", g: "People & Body" },
  { n: "bald_man", c: "👨‍🦲", g: "People & Body" },
  { n: "woman", c: "👩", g: "People & Body" },
  { n: "red_haired_woman", c: "👩‍🦰", g: "People & Body" },
  { n: "red_haired_person", c: "🧑‍🦰", g: "People & Body" },
  { n: "curly_haired_woman", c: "👩‍🦱", g: "People & Body" },
  { n: "curly_haired_person", c: "🧑‍🦱", g: "People & Body" },
  { n: "white_haired_woman", c: "👩‍🦳", g: "People & Body" },
  { n: "white_haired_person", c: "🧑‍🦳", g: "People & Body" },
  { n: "bald_woman", c: "👩‍🦲", g: "People & Body" },
  { n: "bald_person", c: "🧑‍🦲", g: "People & Body" },
  { n: "blond-haired-woman", c: "👱‍♀️", g: "People & Body" },
  { n: "blond-haired-man", c: "👱‍♂️", g: "People & Body" },
  { n: "older_adult", c: "🧓", g: "People & Body" },
  { n: "older_man", c: "👴", g: "People & Body" },
  { n: "older_woman", c: "👵", g: "People & Body" },
  { n: "person_frowning", c: "🙍", g: "People & Body" },
  { n: "man-frowning", c: "🙍‍♂️", g: "People & Body" },
  { n: "woman-frowning", c: "🙍‍♀️", g: "People & Body" },
  { n: "person_with_pouting_face", c: "🙎", g: "People & Body" },
  { n: "man-pouting", c: "🙎‍♂️", g: "People & Body" },
  { n: "woman-pouting", c: "🙎‍♀️", g: "People & Body" },
  { n: "no_good", c: "🙅", g: "People & Body" },
  { n: "man-gesturing-no", c: "🙅‍♂️", g: "People & Body" },
  { n: "woman-gesturing-no", c: "🙅‍♀️", g: "People & Body" },
  { n: "ok_woman", c: "🙆", g: "People & Body" },
  { n: "man-gesturing-ok", c: "🙆‍♂️", g: "People & Body" },
  { n: "woman-gesturing-ok", c: "🙆‍♀️", g: "People & Body" },
  { n: "information_desk_person", c: "💁", g: "People & Body" },
  { n: "man-tipping-hand", c: "💁‍♂️", g: "People & Body" },
  { n: "woman-tipping-hand", c: "💁‍♀️", g: "People & Body" },
  { n: "raising_hand", c: "🙋", g: "People & Body" },
  { n: "man-raising-hand", c: "🙋‍♂️", g: "People & Body" },
  { n: "woman-raising-hand", c: "🙋‍♀️", g: "People & Body" },
  { n: "deaf_person", c: "🧏", g: "People & Body" },
  { n: "deaf_man", c: "🧏‍♂️", g: "People & Body" },
  { n: "deaf_woman", c: "🧏‍♀️", g: "People & Body" },
  { n: "bow", c: "🙇", g: "People & Body" },
  { n: "man-bowing", c: "🙇‍♂️", g: "People & Body" },
  { n: "woman-bowing", c: "🙇‍♀️", g: "People & Body" },
  { n: "face_palm", c: "🤦", g: "People & Body" },
  { n: "man-facepalming", c: "🤦‍♂️", g: "People & Body" },
  { n: "woman-facepalming", c: "🤦‍♀️", g: "People & Body" },
  { n: "shrug", c: "🤷", g: "People & Body" },
  { n: "man-shrugging", c: "🤷‍♂️", g: "People & Body" },
  { n: "woman-shrugging", c: "🤷‍♀️", g: "People & Body" },
  { n: "health_worker", c: "🧑‍⚕️", g: "People & Body" },
  { n: "male-doctor", c: "👨‍⚕️", g: "People & Body" },
  { n: "female-doctor", c: "👩‍⚕️", g: "People & Body" },
  { n: "student", c: "🧑‍🎓", g: "People & Body" },
  { n: "male-student", c: "👨‍🎓", g: "People & Body" },
  { n: "female-student", c: "👩‍🎓", g: "People & Body" },
  { n: "teacher", c: "🧑‍🏫", g: "People & Body" },
  { n: "male-teacher", c: "👨‍🏫", g: "People & Body" },
  { n: "female-teacher", c: "👩‍🏫", g: "People & Body" },
  { n: "judge", c: "🧑‍⚖️", g: "People & Body" },
  { n: "male-judge", c: "👨‍⚖️", g: "People & Body" },
  { n: "female-judge", c: "👩‍⚖️", g: "People & Body" },
  { n: "farmer", c: "🧑‍🌾", g: "People & Body" },
  { n: "male-farmer", c: "👨‍🌾", g: "People & Body" },
  { n: "female-farmer", c: "👩‍🌾", g: "People & Body" },
  { n: "cook", c: "🧑‍🍳", g: "People & Body" },
  { n: "male-cook", c: "👨‍🍳", g: "People & Body" },
  { n: "female-cook", c: "👩‍🍳", g: "People & Body" },
  { n: "mechanic", c: "🧑‍🔧", g: "People & Body" },
  { n: "male-mechanic", c: "👨‍🔧", g: "People & Body" },
  { n: "female-mechanic", c: "👩‍🔧", g: "People & Body" },
  { n: "factory_worker", c: "🧑‍🏭", g: "People & Body" },
  { n: "male-factory-worker", c: "👨‍🏭", g: "People & Body" },
  { n: "female-factory-worker", c: "👩‍🏭", g: "People & Body" },
  { n: "office_worker", c: "🧑‍💼", g: "People & Body" },
  { n: "male-office-worker", c: "👨‍💼", g: "People & Body" },
  { n: "female-office-worker", c: "👩‍💼", g: "People & Body" },
  { n: "scientist", c: "🧑‍🔬", g: "People & Body" },
  { n: "male-scientist", c: "👨‍🔬", g: "People & Body" },
  { n: "female-scientist", c: "👩‍🔬", g: "People & Body" },
  { n: "technologist", c: "🧑‍💻", g: "People & Body" },
  { n: "male-technologist", c: "👨‍💻", g: "People & Body" },
  { n: "female-technologist", c: "👩‍💻", g: "People & Body" },
  { n: "singer", c: "🧑‍🎤", g: "People & Body" },
  { n: "male-singer", c: "👨‍🎤", g: "People & Body" },
  { n: "female-singer", c: "👩‍🎤", g: "People & Body" },
  { n: "artist", c: "🧑‍🎨", g: "People & Body" },
  { n: "male-artist", c: "👨‍🎨", g: "People & Body" },
  { n: "female-artist", c: "👩‍🎨", g: "People & Body" },
  { n: "pilot", c: "🧑‍✈️", g: "People & Body" },
  { n: "male-pilot", c: "👨‍✈️", g: "People & Body" },
  { n: "female-pilot", c: "👩‍✈️", g: "People & Body" },
  { n: "astronaut", c: "🧑‍🚀", g: "People & Body" },
  { n: "male-astronaut", c: "👨‍🚀", g: "People & Body" },
  { n: "female-astronaut", c: "👩‍🚀", g: "People & Body" },
  { n: "firefighter", c: "🧑‍🚒", g: "People & Body" },
  { n: "male-firefighter", c: "👨‍🚒", g: "People & Body" },
  { n: "female-firefighter", c: "👩‍🚒", g: "People & Body" },
  { n: "cop", c: "👮", g: "People & Body" },
  { n: "male-police-officer", c: "👮‍♂️", g: "People & Body" },
  { n: "female-police-officer", c: "👮‍♀️", g: "People & Body" },
  { n: "sleuth_or_spy", c: "🕵️", g: "People & Body" },
  { n: "male-detective", c: "🕵️‍♂️", g: "People & Body" },
  { n: "female-detective", c: "🕵️‍♀️", g: "People & Body" },
  { n: "guardsman", c: "💂", g: "People & Body" },
  { n: "male-guard", c: "💂‍♂️", g: "People & Body" },
  { n: "female-guard", c: "💂‍♀️", g: "People & Body" },
  { n: "ninja", c: "🥷", g: "People & Body" },
  { n: "construction_worker", c: "👷", g: "People & Body" },
  { n: "male-construction-worker", c: "👷‍♂️", g: "People & Body" },
  { n: "female-construction-worker", c: "👷‍♀️", g: "People & Body" },
  { n: "person_with_crown", c: "🫅", g: "People & Body" },
  { n: "prince", c: "🤴", g: "People & Body" },
  { n: "princess", c: "👸", g: "People & Body" },
  { n: "man_with_turban", c: "👳", g: "People & Body" },
  { n: "man-wearing-turban", c: "👳‍♂️", g: "People & Body" },
  { n: "woman-wearing-turban", c: "👳‍♀️", g: "People & Body" },
  { n: "man_with_gua_pi_mao", c: "👲", g: "People & Body" },
  { n: "person_with_headscarf", c: "🧕", g: "People & Body" },
  { n: "person_in_tuxedo", c: "🤵", g: "People & Body" },
  { n: "man_in_tuxedo", c: "🤵‍♂️", g: "People & Body" },
  { n: "woman_in_tuxedo", c: "🤵‍♀️", g: "People & Body" },
  { n: "bride_with_veil", c: "👰", g: "People & Body" },
  { n: "man_with_veil", c: "👰‍♂️", g: "People & Body" },
  { n: "woman_with_veil", c: "👰‍♀️", g: "People & Body" },
  { n: "pregnant_woman", c: "🤰", g: "People & Body" },
  { n: "pregnant_man", c: "🫃", g: "People & Body" },
  { n: "pregnant_person", c: "🫄", g: "People & Body" },
  { n: "breast-feeding", c: "🤱", g: "People & Body" },
  { n: "woman_feeding_baby", c: "👩‍🍼", g: "People & Body" },
  { n: "man_feeding_baby", c: "👨‍🍼", g: "People & Body" },
  { n: "person_feeding_baby", c: "🧑‍🍼", g: "People & Body" },
  { n: "angel", c: "👼", g: "People & Body" },
  { n: "santa", c: "🎅", g: "People & Body" },
  { n: "mrs_claus", c: "🤶", g: "People & Body", a: ["mother_christmas"] },
  { n: "mx_claus", c: "🧑‍🎄", g: "People & Body" },
  { n: "superhero", c: "🦸", g: "People & Body" },
  { n: "male_superhero", c: "🦸‍♂️", g: "People & Body" },
  { n: "female_superhero", c: "🦸‍♀️", g: "People & Body" },
  { n: "supervillain", c: "🦹", g: "People & Body" },
  { n: "male_supervillain", c: "🦹‍♂️", g: "People & Body" },
  { n: "female_supervillain", c: "🦹‍♀️", g: "People & Body" },
  { n: "mage", c: "🧙", g: "People & Body" },
  { n: "male_mage", c: "🧙‍♂️", g: "People & Body" },
  { n: "female_mage", c: "🧙‍♀️", g: "People & Body" },
  { n: "fairy", c: "🧚", g: "People & Body" },
  { n: "male_fairy", c: "🧚‍♂️", g: "People & Body" },
  { n: "female_fairy", c: "🧚‍♀️", g: "People & Body" },
  { n: "vampire", c: "🧛", g: "People & Body" },
  { n: "male_vampire", c: "🧛‍♂️", g: "People & Body" },
  { n: "female_vampire", c: "🧛‍♀️", g: "People & Body" },
  { n: "merperson", c: "🧜", g: "People & Body" },
  { n: "merman", c: "🧜‍♂️", g: "People & Body" },
  { n: "mermaid", c: "🧜‍♀️", g: "People & Body" },
  { n: "elf", c: "🧝", g: "People & Body" },
  { n: "male_elf", c: "🧝‍♂️", g: "People & Body" },
  { n: "female_elf", c: "🧝‍♀️", g: "People & Body" },
  { n: "genie", c: "🧞", g: "People & Body" },
  { n: "male_genie", c: "🧞‍♂️", g: "People & Body" },
  { n: "female_genie", c: "🧞‍♀️", g: "People & Body" },
  { n: "zombie", c: "🧟", g: "People & Body" },
  { n: "male_zombie", c: "🧟‍♂️", g: "People & Body" },
  { n: "female_zombie", c: "🧟‍♀️", g: "People & Body" },
  { n: "troll", c: "🧌", g: "People & Body" },
  { n: "massage", c: "💆", g: "People & Body" },
  { n: "man-getting-massage", c: "💆‍♂️", g: "People & Body" },
  { n: "woman-getting-massage", c: "💆‍♀️", g: "People & Body" },
  { n: "haircut", c: "💇", g: "People & Body" },
  { n: "man-getting-haircut", c: "💇‍♂️", g: "People & Body" },
  { n: "woman-getting-haircut", c: "💇‍♀️", g: "People & Body" },
  { n: "walking", c: "🚶", g: "People & Body" },
  { n: "man-walking", c: "🚶‍♂️", g: "People & Body" },
  { n: "woman-walking", c: "🚶‍♀️", g: "People & Body" },
  { n: "person_walking_facing_right", c: "🚶‍➡️", g: "People & Body" },
  { n: "woman_walking_facing_right", c: "🚶‍♀️‍➡️", g: "People & Body" },
  { n: "man_walking_facing_right", c: "🚶‍♂️‍➡️", g: "People & Body" },
  { n: "standing_person", c: "🧍", g: "People & Body" },
  { n: "man_standing", c: "🧍‍♂️", g: "People & Body" },
  { n: "woman_standing", c: "🧍‍♀️", g: "People & Body" },
  { n: "kneeling_person", c: "🧎", g: "People & Body" },
  { n: "man_kneeling", c: "🧎‍♂️", g: "People & Body" },
  { n: "woman_kneeling", c: "🧎‍♀️", g: "People & Body" },
  { n: "person_kneeling_facing_right", c: "🧎‍➡️", g: "People & Body" },
  { n: "woman_kneeling_facing_right", c: "🧎‍♀️‍➡️", g: "People & Body" },
  { n: "man_kneeling_facing_right", c: "🧎‍♂️‍➡️", g: "People & Body" },
  { n: "person_with_probing_cane", c: "🧑‍🦯", g: "People & Body" },
  { n: "person_with_white_cane_facing_right", c: "🧑‍🦯‍➡️", g: "People & Body" },
  { n: "man_with_probing_cane", c: "👨‍🦯", g: "People & Body" },
  { n: "man_with_white_cane_facing_right", c: "👨‍🦯‍➡️", g: "People & Body" },
  { n: "woman_with_probing_cane", c: "👩‍🦯", g: "People & Body" },
  { n: "woman_with_white_cane_facing_right", c: "👩‍🦯‍➡️", g: "People & Body" },
  { n: "person_in_motorized_wheelchair", c: "🧑‍🦼", g: "People & Body" },
  { n: "person_in_motorized_wheelchair_facing_right", c: "🧑‍🦼‍➡️", g: "People & Body" },
  { n: "man_in_motorized_wheelchair", c: "👨‍🦼", g: "People & Body" },
  { n: "man_in_motorized_wheelchair_facing_right", c: "👨‍🦼‍➡️", g: "People & Body" },
  { n: "woman_in_motorized_wheelchair", c: "👩‍🦼", g: "People & Body" },
  { n: "woman_in_motorized_wheelchair_facing_right", c: "👩‍🦼‍➡️", g: "People & Body" },
  { n: "person_in_manual_wheelchair", c: "🧑‍🦽", g: "People & Body" },
  { n: "person_in_manual_wheelchair_facing_right", c: "🧑‍🦽‍➡️", g: "People & Body" },
  { n: "man_in_manual_wheelchair", c: "👨‍🦽", g: "People & Body" },
  { n: "man_in_manual_wheelchair_facing_right", c: "👨‍🦽‍➡️", g: "People & Body" },
  { n: "woman_in_manual_wheelchair", c: "👩‍🦽", g: "People & Body" },
  { n: "woman_in_manual_wheelchair_facing_right", c: "👩‍🦽‍➡️", g: "People & Body" },
  { n: "runner", c: "🏃", g: "People & Body", a: ["running"] },
  { n: "man-running", c: "🏃‍♂️", g: "People & Body" },
  { n: "woman-running", c: "🏃‍♀️", g: "People & Body" },
  { n: "person_running_facing_right", c: "🏃‍➡️", g: "People & Body" },
  { n: "woman_running_facing_right", c: "🏃‍♀️‍➡️", g: "People & Body" },
  { n: "man_running_facing_right", c: "🏃‍♂️‍➡️", g: "People & Body" },
  { n: "dancer", c: "💃", g: "People & Body" },
  { n: "man_dancing", c: "🕺", g: "People & Body" },
  { n: "man_in_business_suit_levitating", c: "🕴️", g: "People & Body" },
  { n: "dancers", c: "👯", g: "People & Body" },
  { n: "men-with-bunny-ears-partying", c: "👯‍♂️", g: "People & Body", a: ["man-with-bunny-ears-partying"] },
  { n: "women-with-bunny-ears-partying", c: "👯‍♀️", g: "People & Body", a: ["woman-with-bunny-ears-partying"] },
  { n: "person_in_steamy_room", c: "🧖", g: "People & Body" },
  { n: "man_in_steamy_room", c: "🧖‍♂️", g: "People & Body" },
  { n: "woman_in_steamy_room", c: "🧖‍♀️", g: "People & Body" },
  { n: "person_climbing", c: "🧗", g: "People & Body" },
  { n: "man_climbing", c: "🧗‍♂️", g: "People & Body" },
  { n: "woman_climbing", c: "🧗‍♀️", g: "People & Body" },
  { n: "fencer", c: "🤺", g: "People & Body" },
  { n: "horse_racing", c: "🏇", g: "People & Body" },
  { n: "skier", c: "⛷️", g: "People & Body" },
  { n: "snowboarder", c: "🏂", g: "People & Body" },
  { n: "golfer", c: "🏌️", g: "People & Body" },
  { n: "man-golfing", c: "🏌️‍♂️", g: "People & Body" },
  { n: "woman-golfing", c: "🏌️‍♀️", g: "People & Body" },
  { n: "surfer", c: "🏄", g: "People & Body" },
  { n: "man-surfing", c: "🏄‍♂️", g: "People & Body" },
  { n: "woman-surfing", c: "🏄‍♀️", g: "People & Body" },
  { n: "rowboat", c: "🚣", g: "People & Body" },
  { n: "man-rowing-boat", c: "🚣‍♂️", g: "People & Body" },
  { n: "woman-rowing-boat", c: "🚣‍♀️", g: "People & Body" },
  { n: "swimmer", c: "🏊", g: "People & Body" },
  { n: "man-swimming", c: "🏊‍♂️", g: "People & Body" },
  { n: "woman-swimming", c: "🏊‍♀️", g: "People & Body" },
  { n: "person_with_ball", c: "⛹️", g: "People & Body" },
  { n: "man-bouncing-ball", c: "⛹️‍♂️", g: "People & Body" },
  { n: "woman-bouncing-ball", c: "⛹️‍♀️", g: "People & Body" },
  { n: "weight_lifter", c: "🏋️", g: "People & Body" },
  { n: "man-lifting-weights", c: "🏋️‍♂️", g: "People & Body" },
  { n: "woman-lifting-weights", c: "🏋️‍♀️", g: "People & Body" },
  { n: "bicyclist", c: "🚴", g: "People & Body" },
  { n: "man-biking", c: "🚴‍♂️", g: "People & Body" },
  { n: "woman-biking", c: "🚴‍♀️", g: "People & Body" },
  { n: "mountain_bicyclist", c: "🚵", g: "People & Body" },
  { n: "man-mountain-biking", c: "🚵‍♂️", g: "People & Body" },
  { n: "woman-mountain-biking", c: "🚵‍♀️", g: "People & Body" },
  { n: "person_doing_cartwheel", c: "🤸", g: "People & Body" },
  { n: "man-cartwheeling", c: "🤸‍♂️", g: "People & Body" },
  { n: "woman-cartwheeling", c: "🤸‍♀️", g: "People & Body" },
  { n: "wrestlers", c: "🤼", g: "People & Body" },
  { n: "man-wrestling", c: "🤼‍♂️", g: "People & Body" },
  { n: "woman-wrestling", c: "🤼‍♀️", g: "People & Body" },
  { n: "water_polo", c: "🤽", g: "People & Body" },
  { n: "man-playing-water-polo", c: "🤽‍♂️", g: "People & Body" },
  { n: "woman-playing-water-polo", c: "🤽‍♀️", g: "People & Body" },
  { n: "handball", c: "🤾", g: "People & Body" },
  { n: "man-playing-handball", c: "🤾‍♂️", g: "People & Body" },
  { n: "woman-playing-handball", c: "🤾‍♀️", g: "People & Body" },
  { n: "juggling", c: "🤹", g: "People & Body" },
  { n: "man-juggling", c: "🤹‍♂️", g: "People & Body" },
  { n: "woman-juggling", c: "🤹‍♀️", g: "People & Body" },
  { n: "person_in_lotus_position", c: "🧘", g: "People & Body" },
  { n: "man_in_lotus_position", c: "🧘‍♂️", g: "People & Body" },
  { n: "woman_in_lotus_position", c: "🧘‍♀️", g: "People & Body" },
  { n: "bath", c: "🛀", g: "People & Body" },
  { n: "sleeping_accommodation", c: "🛌", g: "People & Body" },
  { n: "people_holding_hands", c: "🧑‍🤝‍🧑", g: "People & Body" },
  { n: "two_women_holding_hands", c: "👭", g: "People & Body", a: ["women_holding_hands"] },
  { n: "man_and_woman_holding_hands", c: "👫", g: "People & Body", a: ["woman_and_man_holding_hands", "couple"] },
  { n: "two_men_holding_hands", c: "👬", g: "People & Body", a: ["men_holding_hands"] },
  { n: "couplekiss", c: "💏", g: "People & Body" },
  { n: "woman-kiss-man", c: "👩‍❤️‍💋‍👨", g: "People & Body" },
  { n: "man-kiss-man", c: "👨‍❤️‍💋‍👨", g: "People & Body" },
  { n: "woman-kiss-woman", c: "👩‍❤️‍💋‍👩", g: "People & Body" },
  { n: "couple_with_heart", c: "💑", g: "People & Body" },
  { n: "woman-heart-man", c: "👩‍❤️‍👨", g: "People & Body" },
  { n: "man-heart-man", c: "👨‍❤️‍👨", g: "People & Body" },
  { n: "woman-heart-woman", c: "👩‍❤️‍👩", g: "People & Body" },
  { n: "man-woman-boy", c: "👨‍👩‍👦", g: "People & Body" },
  { n: "man-woman-girl", c: "👨‍👩‍👧", g: "People & Body" },
  { n: "man-woman-girl-boy", c: "👨‍👩‍👧‍👦", g: "People & Body" },
  { n: "man-woman-boy-boy", c: "👨‍👩‍👦‍👦", g: "People & Body" },
  { n: "man-woman-girl-girl", c: "👨‍👩‍👧‍👧", g: "People & Body" },
  { n: "man-man-boy", c: "👨‍👨‍👦", g: "People & Body" },
  { n: "man-man-girl", c: "👨‍👨‍👧", g: "People & Body" },
  { n: "man-man-girl-boy", c: "👨‍👨‍👧‍👦", g: "People & Body" },
  { n: "man-man-boy-boy", c: "👨‍👨‍👦‍👦", g: "People & Body" },
  { n: "man-man-girl-girl", c: "👨‍👨‍👧‍👧", g: "People & Body" },
  { n: "woman-woman-boy", c: "👩‍👩‍👦", g: "People & Body" },
  { n: "woman-woman-girl", c: "👩‍👩‍👧", g: "People & Body" },
  { n: "woman-woman-girl-boy", c: "👩‍👩‍👧‍👦", g: "People & Body" },
  { n: "woman-woman-boy-boy", c: "👩‍👩‍👦‍👦", g: "People & Body" },
  { n: "woman-woman-girl-girl", c: "👩‍👩‍👧‍👧", g: "People & Body" },
  { n: "man-boy", c: "👨‍👦", g: "People & Body" },
  { n: "man-boy-boy", c: "👨‍👦‍👦", g: "People & Body" },
  { n: "man-girl", c: "👨‍👧", g: "People & Body" },
  { n: "man-girl-boy", c: "👨‍👧‍👦", g: "People & Body" },
  { n: "man-girl-girl", c: "👨‍👧‍👧", g: "People & Body" },
  { n: "woman-boy", c: "👩‍👦", g: "People & Body" },
  { n: "woman-boy-boy", c: "👩‍👦‍👦", g: "People & Body" },
  { n: "woman-girl", c: "👩‍👧", g: "People & Body" },
  { n: "woman-girl-boy", c: "👩‍👧‍👦", g: "People & Body" },
  { n: "woman-girl-girl", c: "👩‍👧‍👧", g: "People & Body" },
  { n: "speaking_head_in_silhouette", c: "🗣️", g: "People & Body" },
  { n: "bust_in_silhouette", c: "👤", g: "People & Body" },
  { n: "busts_in_silhouette", c: "👥", g: "People & Body" },
  { n: "people_hugging", c: "🫂", g: "People & Body" },
  { n: "family", c: "👪", g: "People & Body" },
  { n: "family_adult_adult_child", c: "🧑‍🧑‍🧒", g: "People & Body" },
  { n: "family_adult_adult_child_child", c: "🧑‍🧑‍🧒‍🧒", g: "People & Body" },
  { n: "family_adult_child", c: "🧑‍🧒", g: "People & Body" },
  { n: "family_adult_child_child", c: "🧑‍🧒‍🧒", g: "People & Body" },
  { n: "footprints", c: "👣", g: "People & Body" },
  { n: "fingerprint", c: "🫆", g: "People & Body" },
  { n: "monkey_face", c: "🐵", g: "Animals & Nature" },
  { n: "monkey", c: "🐒", g: "Animals & Nature" },
  { n: "gorilla", c: "🦍", g: "Animals & Nature" },
  { n: "orangutan", c: "🦧", g: "Animals & Nature" },
  { n: "dog", c: "🐶", g: "Animals & Nature" },
  { n: "dog2", c: "🐕", g: "Animals & Nature" },
  { n: "guide_dog", c: "🦮", g: "Animals & Nature" },
  { n: "service_dog", c: "🐕‍🦺", g: "Animals & Nature" },
  { n: "poodle", c: "🐩", g: "Animals & Nature" },
  { n: "wolf", c: "🐺", g: "Animals & Nature" },
  { n: "fox_face", c: "🦊", g: "Animals & Nature" },
  { n: "raccoon", c: "🦝", g: "Animals & Nature" },
  { n: "cat", c: "🐱", g: "Animals & Nature" },
  { n: "cat2", c: "🐈", g: "Animals & Nature" },
  { n: "black_cat", c: "🐈‍⬛", g: "Animals & Nature" },
  { n: "lion_face", c: "🦁", g: "Animals & Nature" },
  { n: "tiger", c: "🐯", g: "Animals & Nature" },
  { n: "tiger2", c: "🐅", g: "Animals & Nature" },
  { n: "leopard", c: "🐆", g: "Animals & Nature" },
  { n: "horse", c: "🐴", g: "Animals & Nature" },
  { n: "moose", c: "🫎", g: "Animals & Nature" },
  { n: "donkey", c: "🫏", g: "Animals & Nature" },
  { n: "racehorse", c: "🐎", g: "Animals & Nature" },
  { n: "unicorn_face", c: "🦄", g: "Animals & Nature" },
  { n: "zebra_face", c: "🦓", g: "Animals & Nature" },
  { n: "deer", c: "🦌", g: "Animals & Nature" },
  { n: "bison", c: "🦬", g: "Animals & Nature" },
  { n: "cow", c: "🐮", g: "Animals & Nature" },
  { n: "ox", c: "🐂", g: "Animals & Nature" },
  { n: "water_buffalo", c: "🐃", g: "Animals & Nature" },
  { n: "cow2", c: "🐄", g: "Animals & Nature" },
  { n: "pig", c: "🐷", g: "Animals & Nature" },
  { n: "pig2", c: "🐖", g: "Animals & Nature" },
  { n: "boar", c: "🐗", g: "Animals & Nature" },
  { n: "pig_nose", c: "🐽", g: "Animals & Nature" },
  { n: "ram", c: "🐏", g: "Animals & Nature" },
  { n: "sheep", c: "🐑", g: "Animals & Nature" },
  { n: "goat", c: "🐐", g: "Animals & Nature" },
  { n: "dromedary_camel", c: "🐪", g: "Animals & Nature" },
  { n: "camel", c: "🐫", g: "Animals & Nature" },
  { n: "llama", c: "🦙", g: "Animals & Nature" },
  { n: "giraffe_face", c: "🦒", g: "Animals & Nature" },
  { n: "elephant", c: "🐘", g: "Animals & Nature" },
  { n: "mammoth", c: "🦣", g: "Animals & Nature" },
  { n: "rhinoceros", c: "🦏", g: "Animals & Nature" },
  { n: "hippopotamus", c: "🦛", g: "Animals & Nature" },
  { n: "mouse", c: "🐭", g: "Animals & Nature" },
  { n: "mouse2", c: "🐁", g: "Animals & Nature" },
  { n: "rat", c: "🐀", g: "Animals & Nature" },
  { n: "hamster", c: "🐹", g: "Animals & Nature" },
  { n: "rabbit", c: "🐰", g: "Animals & Nature" },
  { n: "rabbit2", c: "🐇", g: "Animals & Nature" },
  { n: "chipmunk", c: "🐿️", g: "Animals & Nature" },
  { n: "beaver", c: "🦫", g: "Animals & Nature" },
  { n: "hedgehog", c: "🦔", g: "Animals & Nature" },
  { n: "bat", c: "🦇", g: "Animals & Nature" },
  { n: "bear", c: "🐻", g: "Animals & Nature" },
  { n: "polar_bear", c: "🐻‍❄️", g: "Animals & Nature" },
  { n: "koala", c: "🐨", g: "Animals & Nature" },
  { n: "panda_face", c: "🐼", g: "Animals & Nature" },
  { n: "sloth", c: "🦥", g: "Animals & Nature" },
  { n: "otter", c: "🦦", g: "Animals & Nature" },
  { n: "skunk", c: "🦨", g: "Animals & Nature" },
  { n: "kangaroo", c: "🦘", g: "Animals & Nature" },
  { n: "badger", c: "🦡", g: "Animals & Nature" },
  { n: "feet", c: "🐾", g: "Animals & Nature", a: ["paw_prints"] },
  { n: "turkey", c: "🦃", g: "Animals & Nature" },
  { n: "chicken", c: "🐔", g: "Animals & Nature" },
  { n: "rooster", c: "🐓", g: "Animals & Nature" },
  { n: "hatching_chick", c: "🐣", g: "Animals & Nature" },
  { n: "baby_chick", c: "🐤", g: "Animals & Nature" },
  { n: "hatched_chick", c: "🐥", g: "Animals & Nature" },
  { n: "bird", c: "🐦", g: "Animals & Nature" },
  { n: "penguin", c: "🐧", g: "Animals & Nature" },
  { n: "dove_of_peace", c: "🕊️", g: "Animals & Nature" },
  { n: "eagle", c: "🦅", g: "Animals & Nature" },
  { n: "duck", c: "🦆", g: "Animals & Nature" },
  { n: "swan", c: "🦢", g: "Animals & Nature" },
  { n: "owl", c: "🦉", g: "Animals & Nature" },
  { n: "dodo", c: "🦤", g: "Animals & Nature" },
  { n: "feather", c: "🪶", g: "Animals & Nature" },
  { n: "flamingo", c: "🦩", g: "Animals & Nature" },
  { n: "peacock", c: "🦚", g: "Animals & Nature" },
  { n: "parrot", c: "🦜", g: "Animals & Nature" },
  { n: "wing", c: "🪽", g: "Animals & Nature" },
  { n: "black_bird", c: "🐦‍⬛", g: "Animals & Nature" },
  { n: "goose", c: "🪿", g: "Animals & Nature" },
  { n: "phoenix", c: "🐦‍🔥", g: "Animals & Nature" },
  { n: "frog", c: "🐸", g: "Animals & Nature" },
  { n: "crocodile", c: "🐊", g: "Animals & Nature" },
  { n: "turtle", c: "🐢", g: "Animals & Nature" },
  { n: "lizard", c: "🦎", g: "Animals & Nature" },
  { n: "snake", c: "🐍", g: "Animals & Nature" },
  { n: "dragon_face", c: "🐲", g: "Animals & Nature" },
  { n: "dragon", c: "🐉", g: "Animals & Nature" },
  { n: "sauropod", c: "🦕", g: "Animals & Nature" },
  { n: "t-rex", c: "🦖", g: "Animals & Nature" },
  { n: "whale", c: "🐳", g: "Animals & Nature" },
  { n: "whale2", c: "🐋", g: "Animals & Nature" },
  { n: "dolphin", c: "🐬", g: "Animals & Nature", a: ["flipper"] },
  { n: "seal", c: "🦭", g: "Animals & Nature" },
  { n: "fish", c: "🐟", g: "Animals & Nature" },
  { n: "tropical_fish", c: "🐠", g: "Animals & Nature" },
  { n: "blowfish", c: "🐡", g: "Animals & Nature" },
  { n: "shark", c: "🦈", g: "Animals & Nature" },
  { n: "octopus", c: "🐙", g: "Animals & Nature" },
  { n: "shell", c: "🐚", g: "Animals & Nature" },
  { n: "coral", c: "🪸", g: "Animals & Nature" },
  { n: "jellyfish", c: "🪼", g: "Animals & Nature" },
  { n: "crab", c: "🦀", g: "Animals & Nature" },
  { n: "lobster", c: "🦞", g: "Animals & Nature" },
  { n: "shrimp", c: "🦐", g: "Animals & Nature" },
  { n: "squid", c: "🦑", g: "Animals & Nature" },
  { n: "oyster", c: "🦪", g: "Animals & Nature" },
  { n: "snail", c: "🐌", g: "Animals & Nature" },
  { n: "butterfly", c: "🦋", g: "Animals & Nature" },
  { n: "bug", c: "🐛", g: "Animals & Nature" },
  { n: "ant", c: "🐜", g: "Animals & Nature" },
  { n: "bee", c: "🐝", g: "Animals & Nature", a: ["honeybee"] },
  { n: "beetle", c: "🪲", g: "Animals & Nature" },
  { n: "ladybug", c: "🐞", g: "Animals & Nature", a: ["lady_beetle"] },
  { n: "cricket", c: "🦗", g: "Animals & Nature" },
  { n: "cockroach", c: "🪳", g: "Animals & Nature" },
  { n: "spider", c: "🕷️", g: "Animals & Nature" },
  { n: "spider_web", c: "🕸️", g: "Animals & Nature" },
  { n: "scorpion", c: "🦂", g: "Animals & Nature" },
  { n: "mosquito", c: "🦟", g: "Animals & Nature" },
  { n: "fly", c: "🪰", g: "Animals & Nature" },
  { n: "worm", c: "🪱", g: "Animals & Nature" },
  { n: "microbe", c: "🦠", g: "Animals & Nature" },
  { n: "bouquet", c: "💐", g: "Animals & Nature" },
  { n: "cherry_blossom", c: "🌸", g: "Animals & Nature" },
  { n: "white_flower", c: "💮", g: "Animals & Nature" },
  { n: "lotus", c: "🪷", g: "Animals & Nature" },
  { n: "rosette", c: "🏵️", g: "Animals & Nature" },
  { n: "rose", c: "🌹", g: "Animals & Nature" },
  { n: "wilted_flower", c: "🥀", g: "Animals & Nature" },
  { n: "hibiscus", c: "🌺", g: "Animals & Nature" },
  { n: "sunflower", c: "🌻", g: "Animals & Nature" },
  { n: "blossom", c: "🌼", g: "Animals & Nature" },
  { n: "tulip", c: "🌷", g: "Animals & Nature" },
  { n: "hyacinth", c: "🪻", g: "Animals & Nature" },
  { n: "seedling", c: "🌱", g: "Animals & Nature" },
  { n: "potted_plant", c: "🪴", g: "Animals & Nature" },
  { n: "evergreen_tree", c: "🌲", g: "Animals & Nature" },
  { n: "deciduous_tree", c: "🌳", g: "Animals & Nature" },
  { n: "palm_tree", c: "🌴", g: "Animals & Nature" },
  { n: "cactus", c: "🌵", g: "Animals & Nature" },
  { n: "ear_of_rice", c: "🌾", g: "Animals & Nature" },
  { n: "herb", c: "🌿", g: "Animals & Nature" },
  { n: "shamrock", c: "☘️", g: "Animals & Nature" },
  { n: "four_leaf_clover", c: "🍀", g: "Animals & Nature" },
  { n: "maple_leaf", c: "🍁", g: "Animals & Nature" },
  { n: "fallen_leaf", c: "🍂", g: "Animals & Nature" },
  { n: "leaves", c: "🍃", g: "Animals & Nature" },
  { n: "empty_nest", c: "🪹", g: "Animals & Nature" },
  { n: "nest_with_eggs", c: "🪺", g: "Animals & Nature" },
  { n: "mushroom", c: "🍄", g: "Animals & Nature" },
  { n: "leafless_tree", c: "🪾", g: "Animals & Nature" },
  { n: "grapes", c: "🍇", g: "Food & Drink" },
  { n: "melon", c: "🍈", g: "Food & Drink" },
  { n: "watermelon", c: "🍉", g: "Food & Drink" },
  { n: "tangerine", c: "🍊", g: "Food & Drink" },
  { n: "lemon", c: "🍋", g: "Food & Drink" },
  { n: "lime", c: "🍋‍🟩", g: "Food & Drink" },
  { n: "banana", c: "🍌", g: "Food & Drink" },
  { n: "pineapple", c: "🍍", g: "Food & Drink" },
  { n: "mango", c: "🥭", g: "Food & Drink" },
  { n: "apple", c: "🍎", g: "Food & Drink" },
  { n: "green_apple", c: "🍏", g: "Food & Drink" },
  { n: "pear", c: "🍐", g: "Food & Drink" },
  { n: "peach", c: "🍑", g: "Food & Drink" },
  { n: "cherries", c: "🍒", g: "Food & Drink" },
  { n: "strawberry", c: "🍓", g: "Food & Drink" },
  { n: "blueberries", c: "🫐", g: "Food & Drink" },
  { n: "kiwifruit", c: "🥝", g: "Food & Drink" },
  { n: "tomato", c: "🍅", g: "Food & Drink" },
  { n: "olive", c: "🫒", g: "Food & Drink" },
  { n: "coconut", c: "🥥", g: "Food & Drink" },
  { n: "avocado", c: "🥑", g: "Food & Drink" },
  { n: "eggplant", c: "🍆", g: "Food & Drink" },
  { n: "potato", c: "🥔", g: "Food & Drink" },
  { n: "carrot", c: "🥕", g: "Food & Drink" },
  { n: "corn", c: "🌽", g: "Food & Drink" },
  { n: "hot_pepper", c: "🌶️", g: "Food & Drink" },
  { n: "bell_pepper", c: "🫑", g: "Food & Drink" },
  { n: "cucumber", c: "🥒", g: "Food & Drink" },
  { n: "leafy_green", c: "🥬", g: "Food & Drink" },
  { n: "broccoli", c: "🥦", g: "Food & Drink" },
  { n: "garlic", c: "🧄", g: "Food & Drink" },
  { n: "onion", c: "🧅", g: "Food & Drink" },
  { n: "peanuts", c: "🥜", g: "Food & Drink" },
  { n: "beans", c: "🫘", g: "Food & Drink" },
  { n: "chestnut", c: "🌰", g: "Food & Drink" },
  { n: "ginger_root", c: "🫚", g: "Food & Drink" },
  { n: "pea_pod", c: "🫛", g: "Food & Drink" },
  { n: "brown_mushroom", c: "🍄‍🟫", g: "Food & Drink" },
  { n: "root_vegetable", c: "🫜", g: "Food & Drink" },
  { n: "bread", c: "🍞", g: "Food & Drink" },
  { n: "croissant", c: "🥐", g: "Food & Drink" },
  { n: "baguette_bread", c: "🥖", g: "Food & Drink" },
  { n: "flatbread", c: "🫓", g: "Food & Drink" },
  { n: "pretzel", c: "🥨", g: "Food & Drink" },
  { n: "bagel", c: "🥯", g: "Food & Drink" },
  { n: "pancakes", c: "🥞", g: "Food & Drink" },
  { n: "waffle", c: "🧇", g: "Food & Drink" },
  { n: "cheese_wedge", c: "🧀", g: "Food & Drink" },
  { n: "meat_on_bone", c: "🍖", g: "Food & Drink" },
  { n: "poultry_leg", c: "🍗", g: "Food & Drink" },
  { n: "cut_of_meat", c: "🥩", g: "Food & Drink" },
  { n: "bacon", c: "🥓", g: "Food & Drink" },
  { n: "hamburger", c: "🍔", g: "Food & Drink" },
  { n: "fries", c: "🍟", g: "Food & Drink" },
  { n: "pizza", c: "🍕", g: "Food & Drink" },
  { n: "hotdog", c: "🌭", g: "Food & Drink" },
  { n: "sandwich", c: "🥪", g: "Food & Drink" },
  { n: "taco", c: "🌮", g: "Food & Drink" },
  { n: "burrito", c: "🌯", g: "Food & Drink" },
  { n: "tamale", c: "🫔", g: "Food & Drink" },
  { n: "stuffed_flatbread", c: "🥙", g: "Food & Drink" },
  { n: "falafel", c: "🧆", g: "Food & Drink" },
  { n: "egg", c: "🥚", g: "Food & Drink" },
  { n: "fried_egg", c: "🍳", g: "Food & Drink", a: ["cooking"] },
  { n: "shallow_pan_of_food", c: "🥘", g: "Food & Drink" },
  { n: "stew", c: "🍲", g: "Food & Drink" },
  { n: "fondue", c: "🫕", g: "Food & Drink" },
  { n: "bowl_with_spoon", c: "🥣", g: "Food & Drink" },
  { n: "green_salad", c: "🥗", g: "Food & Drink" },
  { n: "popcorn", c: "🍿", g: "Food & Drink" },
  { n: "butter", c: "🧈", g: "Food & Drink" },
  { n: "salt", c: "🧂", g: "Food & Drink" },
  { n: "canned_food", c: "🥫", g: "Food & Drink" },
  { n: "bento", c: "🍱", g: "Food & Drink" },
  { n: "rice_cracker", c: "🍘", g: "Food & Drink" },
  { n: "rice_ball", c: "🍙", g: "Food & Drink" },
  { n: "rice", c: "🍚", g: "Food & Drink" },
  { n: "curry", c: "🍛", g: "Food & Drink" },
  { n: "ramen", c: "🍜", g: "Food & Drink" },
  { n: "spaghetti", c: "🍝", g: "Food & Drink" },
  { n: "sweet_potato", c: "🍠", g: "Food & Drink" },
  { n: "oden", c: "🍢", g: "Food & Drink" },
  { n: "sushi", c: "🍣", g: "Food & Drink" },
  { n: "fried_shrimp", c: "🍤", g: "Food & Drink" },
  { n: "fish_cake", c: "🍥", g: "Food & Drink" },
  { n: "moon_cake", c: "🥮", g: "Food & Drink" },
  { n: "dango", c: "🍡", g: "Food & Drink" },
  { n: "dumpling", c: "🥟", g: "Food & Drink" },
  { n: "fortune_cookie", c: "🥠", g: "Food & Drink" },
  { n: "takeout_box", c: "🥡", g: "Food & Drink" },
  { n: "icecream", c: "🍦", g: "Food & Drink" },
  { n: "shaved_ice", c: "🍧", g: "Food & Drink" },
  { n: "ice_cream", c: "🍨", g: "Food & Drink" },
  { n: "doughnut", c: "🍩", g: "Food & Drink" },
  { n: "cookie", c: "🍪", g: "Food & Drink" },
  { n: "birthday", c: "🎂", g: "Food & Drink" },
  { n: "cake", c: "🍰", g: "Food & Drink" },
  { n: "cupcake", c: "🧁", g: "Food & Drink" },
  { n: "pie", c: "🥧", g: "Food & Drink" },
  { n: "chocolate_bar", c: "🍫", g: "Food & Drink" },
  { n: "candy", c: "🍬", g: "Food & Drink" },
  { n: "lollipop", c: "🍭", g: "Food & Drink" },
  { n: "custard", c: "🍮", g: "Food & Drink" },
  { n: "honey_pot", c: "🍯", g: "Food & Drink" },
  { n: "baby_bottle", c: "🍼", g: "Food & Drink" },
  { n: "glass_of_milk", c: "🥛", g: "Food & Drink" },
  { n: "coffee", c: "☕", g: "Food & Drink" },
  { n: "teapot", c: "🫖", g: "Food & Drink" },
  { n: "tea", c: "🍵", g: "Food & Drink" },
  { n: "sake", c: "🍶", g: "Food & Drink" },
  { n: "champagne", c: "🍾", g: "Food & Drink" },
  { n: "wine_glass", c: "🍷", g: "Food & Drink" },
  { n: "cocktail", c: "🍸", g: "Food & Drink" },
  { n: "tropical_drink", c: "🍹", g: "Food & Drink" },
  { n: "beer", c: "🍺", g: "Food & Drink" },
  { n: "beers", c: "🍻", g: "Food & Drink" },
  { n: "clinking_glasses", c: "🥂", g: "Food & Drink" },
  { n: "tumbler_glass", c: "🥃", g: "Food & Drink" },
  { n: "pouring_liquid", c: "🫗", g: "Food & Drink" },
  { n: "cup_with_straw", c: "🥤", g: "Food & Drink" },
  { n: "bubble_tea", c: "🧋", g: "Food & Drink" },
  { n: "beverage_box", c: "🧃", g: "Food & Drink" },
  { n: "mate_drink", c: "🧉", g: "Food & Drink" },
  { n: "ice_cube", c: "🧊", g: "Food & Drink" },
  { n: "chopsticks", c: "🥢", g: "Food & Drink" },
  { n: "knife_fork_plate", c: "🍽️", g: "Food & Drink" },
  { n: "fork_and_knife", c: "🍴", g: "Food & Drink" },
  { n: "spoon", c: "🥄", g: "Food & Drink" },
  { n: "hocho", c: "🔪", g: "Food & Drink", a: ["knife"] },
  { n: "jar", c: "🫙", g: "Food & Drink" },
  { n: "amphora", c: "🏺", g: "Food & Drink" },
  { n: "earth_africa", c: "🌍", g: "Travel & Places" },
  { n: "earth_americas", c: "🌎", g: "Travel & Places" },
  { n: "earth_asia", c: "🌏", g: "Travel & Places" },
  { n: "globe_with_meridians", c: "🌐", g: "Travel & Places" },
  { n: "world_map", c: "🗺️", g: "Travel & Places" },
  { n: "japan", c: "🗾", g: "Travel & Places" },
  { n: "compass", c: "🧭", g: "Travel & Places" },
  { n: "snow_capped_mountain", c: "🏔️", g: "Travel & Places" },
  { n: "mountain", c: "⛰️", g: "Travel & Places" },
  { n: "volcano", c: "🌋", g: "Travel & Places" },
  { n: "mount_fuji", c: "🗻", g: "Travel & Places" },
  { n: "camping", c: "🏕️", g: "Travel & Places" },
  { n: "beach_with_umbrella", c: "🏖️", g: "Travel & Places" },
  { n: "desert", c: "🏜️", g: "Travel & Places" },
  { n: "desert_island", c: "🏝️", g: "Travel & Places" },
  { n: "national_park", c: "🏞️", g: "Travel & Places" },
  { n: "stadium", c: "🏟️", g: "Travel & Places" },
  { n: "classical_building", c: "🏛️", g: "Travel & Places" },
  { n: "building_construction", c: "🏗️", g: "Travel & Places" },
  { n: "bricks", c: "🧱", g: "Travel & Places" },
  { n: "rock", c: "🪨", g: "Travel & Places" },
  { n: "wood", c: "🪵", g: "Travel & Places" },
  { n: "hut", c: "🛖", g: "Travel & Places" },
  { n: "house_buildings", c: "🏘️", g: "Travel & Places" },
  { n: "derelict_house_building", c: "🏚️", g: "Travel & Places" },
  { n: "house", c: "🏠", g: "Travel & Places" },
  { n: "house_with_garden", c: "🏡", g: "Travel & Places" },
  { n: "office", c: "🏢", g: "Travel & Places" },
  { n: "post_office", c: "🏣", g: "Travel & Places" },
  { n: "european_post_office", c: "🏤", g: "Travel & Places" },
  { n: "hospital", c: "🏥", g: "Travel & Places" },
  { n: "bank", c: "🏦", g: "Travel & Places" },
  { n: "hotel", c: "🏨", g: "Travel & Places" },
  { n: "love_hotel", c: "🏩", g: "Travel & Places" },
  { n: "convenience_store", c: "🏪", g: "Travel & Places" },
  { n: "school", c: "🏫", g: "Travel & Places" },
  { n: "department_store", c: "🏬", g: "Travel & Places" },
  { n: "factory", c: "🏭", g: "Travel & Places" },
  { n: "japanese_castle", c: "🏯", g: "Travel & Places" },
  { n: "european_castle", c: "🏰", g: "Travel & Places" },
  { n: "wedding", c: "💒", g: "Travel & Places" },
  { n: "tokyo_tower", c: "🗼", g: "Travel & Places" },
  { n: "statue_of_liberty", c: "🗽", g: "Travel & Places" },
  { n: "church", c: "⛪", g: "Travel & Places" },
  { n: "mosque", c: "🕌", g: "Travel & Places" },
  { n: "hindu_temple", c: "🛕", g: "Travel & Places" },
  { n: "synagogue", c: "🕍", g: "Travel & Places" },
  { n: "shinto_shrine", c: "⛩️", g: "Travel & Places" },
  { n: "kaaba", c: "🕋", g: "Travel & Places" },
  { n: "fountain", c: "⛲", g: "Travel & Places" },
  { n: "tent", c: "⛺", g: "Travel & Places" },
  { n: "foggy", c: "🌁", g: "Travel & Places" },
  { n: "night_with_stars", c: "🌃", g: "Travel & Places" },
  { n: "cityscape", c: "🏙️", g: "Travel & Places" },
  { n: "sunrise_over_mountains", c: "🌄", g: "Travel & Places" },
  { n: "sunrise", c: "🌅", g: "Travel & Places" },
  { n: "city_sunset", c: "🌆", g: "Travel & Places" },
  { n: "city_sunrise", c: "🌇", g: "Travel & Places" },
  { n: "bridge_at_night", c: "🌉", g: "Travel & Places" },
  { n: "hotsprings", c: "♨️", g: "Travel & Places" },
  { n: "carousel_horse", c: "🎠", g: "Travel & Places" },
  { n: "playground_slide", c: "🛝", g: "Travel & Places" },
  { n: "ferris_wheel", c: "🎡", g: "Travel & Places" },
  { n: "roller_coaster", c: "🎢", g: "Travel & Places" },
  { n: "barber", c: "💈", g: "Travel & Places" },
  { n: "circus_tent", c: "🎪", g: "Travel & Places" },
  { n: "steam_locomotive", c: "🚂", g: "Travel & Places" },
  { n: "railway_car", c: "🚃", g: "Travel & Places" },
  { n: "bullettrain_side", c: "🚄", g: "Travel & Places" },
  { n: "bullettrain_front", c: "🚅", g: "Travel & Places" },
  { n: "train2", c: "🚆", g: "Travel & Places" },
  { n: "metro", c: "🚇", g: "Travel & Places" },
  { n: "light_rail", c: "🚈", g: "Travel & Places" },
  { n: "station", c: "🚉", g: "Travel & Places" },
  { n: "tram", c: "🚊", g: "Travel & Places" },
  { n: "monorail", c: "🚝", g: "Travel & Places" },
  { n: "mountain_railway", c: "🚞", g: "Travel & Places" },
  { n: "train", c: "🚋", g: "Travel & Places" },
  { n: "bus", c: "🚌", g: "Travel & Places" },
  { n: "oncoming_bus", c: "🚍", g: "Travel & Places" },
  { n: "trolleybus", c: "🚎", g: "Travel & Places" },
  { n: "minibus", c: "🚐", g: "Travel & Places" },
  { n: "ambulance", c: "🚑", g: "Travel & Places" },
  { n: "fire_engine", c: "🚒", g: "Travel & Places" },
  { n: "police_car", c: "🚓", g: "Travel & Places" },
  { n: "oncoming_police_car", c: "🚔", g: "Travel & Places" },
  { n: "taxi", c: "🚕", g: "Travel & Places" },
  { n: "oncoming_taxi", c: "🚖", g: "Travel & Places" },
  { n: "car", c: "🚗", g: "Travel & Places", a: ["red_car"] },
  { n: "oncoming_automobile", c: "🚘", g: "Travel & Places" },
  { n: "blue_car", c: "🚙", g: "Travel & Places" },
  { n: "pickup_truck", c: "🛻", g: "Travel & Places" },
  { n: "truck", c: "🚚", g: "Travel & Places" },
  { n: "articulated_lorry", c: "🚛", g: "Travel & Places" },
  { n: "tractor", c: "🚜", g: "Travel & Places" },
  { n: "racing_car", c: "🏎️", g: "Travel & Places" },
  { n: "racing_motorcycle", c: "🏍️", g: "Travel & Places" },
  { n: "motor_scooter", c: "🛵", g: "Travel & Places" },
  { n: "manual_wheelchair", c: "🦽", g: "Travel & Places" },
  { n: "motorized_wheelchair", c: "🦼", g: "Travel & Places" },
  { n: "auto_rickshaw", c: "🛺", g: "Travel & Places" },
  { n: "bike", c: "🚲", g: "Travel & Places" },
  { n: "scooter", c: "🛴", g: "Travel & Places" },
  { n: "skateboard", c: "🛹", g: "Travel & Places" },
  { n: "roller_skate", c: "🛼", g: "Travel & Places" },
  { n: "busstop", c: "🚏", g: "Travel & Places" },
  { n: "motorway", c: "🛣️", g: "Travel & Places" },
  { n: "railway_track", c: "🛤️", g: "Travel & Places" },
  { n: "oil_drum", c: "🛢️", g: "Travel & Places" },
  { n: "fuelpump", c: "⛽", g: "Travel & Places" },
  { n: "wheel", c: "🛞", g: "Travel & Places" },
  { n: "rotating_light", c: "🚨", g: "Travel & Places" },
  { n: "traffic_light", c: "🚥", g: "Travel & Places" },
  { n: "vertical_traffic_light", c: "🚦", g: "Travel & Places" },
  { n: "octagonal_sign", c: "🛑", g: "Travel & Places" },
  { n: "construction", c: "🚧", g: "Travel & Places" },
  { n: "anchor", c: "⚓", g: "Travel & Places" },
  { n: "ring_buoy", c: "🛟", g: "Travel & Places" },
  { n: "boat", c: "⛵", g: "Travel & Places", a: ["sailboat"] },
  { n: "canoe", c: "🛶", g: "Travel & Places" },
  { n: "speedboat", c: "🚤", g: "Travel & Places" },
  { n: "passenger_ship", c: "🛳️", g: "Travel & Places" },
  { n: "ferry", c: "⛴️", g: "Travel & Places" },
  { n: "motor_boat", c: "🛥️", g: "Travel & Places" },
  { n: "ship", c: "🚢", g: "Travel & Places" },
  { n: "airplane", c: "✈️", g: "Travel & Places" },
  { n: "small_airplane", c: "🛩️", g: "Travel & Places" },
  { n: "airplane_departure", c: "🛫", g: "Travel & Places" },
  { n: "airplane_arriving", c: "🛬", g: "Travel & Places" },
  { n: "parachute", c: "🪂", g: "Travel & Places" },
  { n: "seat", c: "💺", g: "Travel & Places" },
  { n: "helicopter", c: "🚁", g: "Travel & Places" },
  { n: "suspension_railway", c: "🚟", g: "Travel & Places" },
  { n: "mountain_cableway", c: "🚠", g: "Travel & Places" },
  { n: "aerial_tramway", c: "🚡", g: "Travel & Places" },
  { n: "satellite", c: "🛰️", g: "Travel & Places" },
  { n: "rocket", c: "🚀", g: "Travel & Places" },
  { n: "flying_saucer", c: "🛸", g: "Travel & Places" },
  { n: "bellhop_bell", c: "🛎️", g: "Travel & Places" },
  { n: "luggage", c: "🧳", g: "Travel & Places" },
  { n: "hourglass", c: "⌛", g: "Travel & Places" },
  { n: "hourglass_flowing_sand", c: "⏳", g: "Travel & Places" },
  { n: "watch", c: "⌚", g: "Travel & Places" },
  { n: "alarm_clock", c: "⏰", g: "Travel & Places" },
  { n: "stopwatch", c: "⏱️", g: "Travel & Places" },
  { n: "timer_clock", c: "⏲️", g: "Travel & Places" },
  { n: "mantelpiece_clock", c: "🕰️", g: "Travel & Places" },
  { n: "clock12", c: "🕛", g: "Travel & Places" },
  { n: "clock1230", c: "🕧", g: "Travel & Places" },
  { n: "clock1", c: "🕐", g: "Travel & Places" },
  { n: "clock130", c: "🕜", g: "Travel & Places" },
  { n: "clock2", c: "🕑", g: "Travel & Places" },
  { n: "clock230", c: "🕝", g: "Travel & Places" },
  { n: "clock3", c: "🕒", g: "Travel & Places" },
  { n: "clock330", c: "🕞", g: "Travel & Places" },
  { n: "clock4", c: "🕓", g: "Travel & Places" },
  { n: "clock430", c: "🕟", g: "Travel & Places" },
  { n: "clock5", c: "🕔", g: "Travel & Places" },
  { n: "clock530", c: "🕠", g: "Travel & Places" },
  { n: "clock6", c: "🕕", g: "Travel & Places" },
  { n: "clock630", c: "🕡", g: "Travel & Places" },
  { n: "clock7", c: "🕖", g: "Travel & Places" },
  { n: "clock730", c: "🕢", g: "Travel & Places" },
  { n: "clock8", c: "🕗", g: "Travel & Places" },
  { n: "clock830", c: "🕣", g: "Travel & Places" },
  { n: "clock9", c: "🕘", g: "Travel & Places" },
  { n: "clock930", c: "🕤", g: "Travel & Places" },
  { n: "clock10", c: "🕙", g: "Travel & Places" },
  { n: "clock1030", c: "🕥", g: "Travel & Places" },
  { n: "clock11", c: "🕚", g: "Travel & Places" },
  { n: "clock1130", c: "🕦", g: "Travel & Places" },
  { n: "new_moon", c: "🌑", g: "Travel & Places" },
  { n: "waxing_crescent_moon", c: "🌒", g: "Travel & Places" },
  { n: "first_quarter_moon", c: "🌓", g: "Travel & Places" },
  { n: "moon", c: "🌔", g: "Travel & Places", a: ["waxing_gibbous_moon"] },
  { n: "full_moon", c: "🌕", g: "Travel & Places" },
  { n: "waning_gibbous_moon", c: "🌖", g: "Travel & Places" },
  { n: "last_quarter_moon", c: "🌗", g: "Travel & Places" },
  { n: "waning_crescent_moon", c: "🌘", g: "Travel & Places" },
  { n: "crescent_moon", c: "🌙", g: "Travel & Places" },
  { n: "new_moon_with_face", c: "🌚", g: "Travel & Places" },
  { n: "first_quarter_moon_with_face", c: "🌛", g: "Travel & Places" },
  { n: "last_quarter_moon_with_face", c: "🌜", g: "Travel & Places" },
  { n: "thermometer", c: "🌡️", g: "Travel & Places" },
  { n: "sunny", c: "☀️", g: "Travel & Places" },
  { n: "full_moon_with_face", c: "🌝", g: "Travel & Places" },
  { n: "sun_with_face", c: "🌞", g: "Travel & Places" },
  { n: "ringed_planet", c: "🪐", g: "Travel & Places" },
  { n: "star", c: "⭐", g: "Travel & Places" },
  { n: "star2", c: "🌟", g: "Travel & Places" },
  { n: "stars", c: "🌠", g: "Travel & Places" },
  { n: "milky_way", c: "🌌", g: "Travel & Places" },
  { n: "cloud", c: "☁️", g: "Travel & Places" },
  { n: "partly_sunny", c: "⛅", g: "Travel & Places" },
  { n: "thunder_cloud_and_rain", c: "⛈️", g: "Travel & Places" },
  { n: "mostly_sunny", c: "🌤️", g: "Travel & Places", a: ["sun_small_cloud"] },
  { n: "barely_sunny", c: "🌥️", g: "Travel & Places", a: ["sun_behind_cloud"] },
  { n: "partly_sunny_rain", c: "🌦️", g: "Travel & Places", a: ["sun_behind_rain_cloud"] },
  { n: "rain_cloud", c: "🌧️", g: "Travel & Places" },
  { n: "snow_cloud", c: "🌨️", g: "Travel & Places" },
  { n: "lightning", c: "🌩️", g: "Travel & Places", a: ["lightning_cloud"] },
  { n: "tornado", c: "🌪️", g: "Travel & Places", a: ["tornado_cloud"] },
  { n: "fog", c: "🌫️", g: "Travel & Places" },
  { n: "wind_blowing_face", c: "🌬️", g: "Travel & Places" },
  { n: "cyclone", c: "🌀", g: "Travel & Places" },
  { n: "rainbow", c: "🌈", g: "Travel & Places" },
  { n: "closed_umbrella", c: "🌂", g: "Travel & Places" },
  { n: "umbrella", c: "☂️", g: "Travel & Places" },
  { n: "umbrella_with_rain_drops", c: "☔", g: "Travel & Places" },
  { n: "umbrella_on_ground", c: "⛱️", g: "Travel & Places" },
  { n: "zap", c: "⚡", g: "Travel & Places" },
  { n: "snowflake", c: "❄️", g: "Travel & Places" },
  { n: "snowman", c: "☃️", g: "Travel & Places" },
  { n: "snowman_without_snow", c: "⛄", g: "Travel & Places" },
  { n: "comet", c: "☄️", g: "Travel & Places" },
  { n: "fire", c: "🔥", g: "Travel & Places" },
  { n: "droplet", c: "💧", g: "Travel & Places" },
  { n: "ocean", c: "🌊", g: "Travel & Places" },
  { n: "jack_o_lantern", c: "🎃", g: "Activities" },
  { n: "christmas_tree", c: "🎄", g: "Activities" },
  { n: "fireworks", c: "🎆", g: "Activities" },
  { n: "sparkler", c: "🎇", g: "Activities" },
  { n: "firecracker", c: "🧨", g: "Activities" },
  { n: "sparkles", c: "✨", g: "Activities" },
  { n: "balloon", c: "🎈", g: "Activities" },
  { n: "tada", c: "🎉", g: "Activities" },
  { n: "confetti_ball", c: "🎊", g: "Activities" },
  { n: "tanabata_tree", c: "🎋", g: "Activities" },
  { n: "bamboo", c: "🎍", g: "Activities" },
  { n: "dolls", c: "🎎", g: "Activities" },
  { n: "flags", c: "🎏", g: "Activities" },
  { n: "wind_chime", c: "🎐", g: "Activities" },
  { n: "rice_scene", c: "🎑", g: "Activities" },
  { n: "red_envelope", c: "🧧", g: "Activities" },
  { n: "ribbon", c: "🎀", g: "Activities" },
  { n: "gift", c: "🎁", g: "Activities" },
  { n: "reminder_ribbon", c: "🎗️", g: "Activities" },
  { n: "admission_tickets", c: "🎟️", g: "Activities" },
  { n: "ticket", c: "🎫", g: "Activities" },
  { n: "medal", c: "🎖️", g: "Activities" },
  { n: "trophy", c: "🏆", g: "Activities" },
  { n: "sports_medal", c: "🏅", g: "Activities" },
  { n: "first_place_medal", c: "🥇", g: "Activities" },
  { n: "second_place_medal", c: "🥈", g: "Activities" },
  { n: "third_place_medal", c: "🥉", g: "Activities" },
  { n: "soccer", c: "⚽", g: "Activities" },
  { n: "baseball", c: "⚾", g: "Activities" },
  { n: "softball", c: "🥎", g: "Activities" },
  { n: "basketball", c: "🏀", g: "Activities" },
  { n: "volleyball", c: "🏐", g: "Activities" },
  { n: "football", c: "🏈", g: "Activities" },
  { n: "rugby_football", c: "🏉", g: "Activities" },
  { n: "tennis", c: "🎾", g: "Activities" },
  { n: "flying_disc", c: "🥏", g: "Activities" },
  { n: "bowling", c: "🎳", g: "Activities" },
  { n: "cricket_bat_and_ball", c: "🏏", g: "Activities" },
  { n: "field_hockey_stick_and_ball", c: "🏑", g: "Activities" },
  { n: "ice_hockey_stick_and_puck", c: "🏒", g: "Activities" },
  { n: "lacrosse", c: "🥍", g: "Activities" },
  { n: "table_tennis_paddle_and_ball", c: "🏓", g: "Activities" },
  { n: "badminton_racquet_and_shuttlecock", c: "🏸", g: "Activities" },
  { n: "boxing_glove", c: "🥊", g: "Activities" },
  { n: "martial_arts_uniform", c: "🥋", g: "Activities" },
  { n: "goal_net", c: "🥅", g: "Activities" },
  { n: "golf", c: "⛳", g: "Activities" },
  { n: "ice_skate", c: "⛸️", g: "Activities" },
  { n: "fishing_pole_and_fish", c: "🎣", g: "Activities" },
  { n: "diving_mask", c: "🤿", g: "Activities" },
  { n: "running_shirt_with_sash", c: "🎽", g: "Activities" },
  { n: "ski", c: "🎿", g: "Activities" },
  { n: "sled", c: "🛷", g: "Activities" },
  { n: "curling_stone", c: "🥌", g: "Activities" },
  { n: "dart", c: "🎯", g: "Activities" },
  { n: "yo-yo", c: "🪀", g: "Activities" },
  { n: "kite", c: "🪁", g: "Activities" },
  { n: "gun", c: "🔫", g: "Activities" },
  { n: "8ball", c: "🎱", g: "Activities" },
  { n: "crystal_ball", c: "🔮", g: "Activities" },
  { n: "magic_wand", c: "🪄", g: "Activities" },
  { n: "video_game", c: "🎮", g: "Activities" },
  { n: "joystick", c: "🕹️", g: "Activities" },
  { n: "slot_machine", c: "🎰", g: "Activities" },
  { n: "game_die", c: "🎲", g: "Activities" },
  { n: "jigsaw", c: "🧩", g: "Activities" },
  { n: "teddy_bear", c: "🧸", g: "Activities" },
  { n: "pinata", c: "🪅", g: "Activities" },
  { n: "mirror_ball", c: "🪩", g: "Activities" },
  { n: "nesting_dolls", c: "🪆", g: "Activities" },
  { n: "spades", c: "♠️", g: "Activities" },
  { n: "hearts", c: "♥️", g: "Activities" },
  { n: "diamonds", c: "♦️", g: "Activities" },
  { n: "clubs", c: "♣️", g: "Activities" },
  { n: "chess_pawn", c: "♟️", g: "Activities" },
  { n: "black_joker", c: "🃏", g: "Activities" },
  { n: "mahjong", c: "🀄", g: "Activities" },
  { n: "flower_playing_cards", c: "🎴", g: "Activities" },
  { n: "performing_arts", c: "🎭", g: "Activities" },
  { n: "frame_with_picture", c: "🖼️", g: "Activities" },
  { n: "art", c: "🎨", g: "Activities" },
  { n: "thread", c: "🧵", g: "Activities" },
  { n: "sewing_needle", c: "🪡", g: "Activities" },
  { n: "yarn", c: "🧶", g: "Activities" },
  { n: "knot", c: "🪢", g: "Activities" },
  { n: "eyeglasses", c: "👓", g: "Objects" },
  { n: "dark_sunglasses", c: "🕶️", g: "Objects" },
  { n: "goggles", c: "🥽", g: "Objects" },
  { n: "lab_coat", c: "🥼", g: "Objects" },
  { n: "safety_vest", c: "🦺", g: "Objects" },
  { n: "necktie", c: "👔", g: "Objects" },
  { n: "shirt", c: "👕", g: "Objects", a: ["tshirt"] },
  { n: "jeans", c: "👖", g: "Objects" },
  { n: "scarf", c: "🧣", g: "Objects" },
  { n: "gloves", c: "🧤", g: "Objects" },
  { n: "coat", c: "🧥", g: "Objects" },
  { n: "socks", c: "🧦", g: "Objects" },
  { n: "dress", c: "👗", g: "Objects" },
  { n: "kimono", c: "👘", g: "Objects" },
  { n: "sari", c: "🥻", g: "Objects" },
  { n: "one-piece_swimsuit", c: "🩱", g: "Objects" },
  { n: "briefs", c: "🩲", g: "Objects" },
  { n: "shorts", c: "🩳", g: "Objects" },
  { n: "bikini", c: "👙", g: "Objects" },
  { n: "womans_clothes", c: "👚", g: "Objects" },
  { n: "folding_hand_fan", c: "🪭", g: "Objects" },
  { n: "purse", c: "👛", g: "Objects" },
  { n: "handbag", c: "👜", g: "Objects" },
  { n: "pouch", c: "👝", g: "Objects" },
  { n: "shopping_bags", c: "🛍️", g: "Objects" },
  { n: "school_satchel", c: "🎒", g: "Objects" },
  { n: "thong_sandal", c: "🩴", g: "Objects" },
  { n: "mans_shoe", c: "👞", g: "Objects", a: ["shoe"] },
  { n: "athletic_shoe", c: "👟", g: "Objects" },
  { n: "hiking_boot", c: "🥾", g: "Objects" },
  { n: "womans_flat_shoe", c: "🥿", g: "Objects" },
  { n: "high_heel", c: "👠", g: "Objects" },
  { n: "sandal", c: "👡", g: "Objects" },
  { n: "ballet_shoes", c: "🩰", g: "Objects" },
  { n: "boot", c: "👢", g: "Objects" },
  { n: "hair_pick", c: "🪮", g: "Objects" },
  { n: "crown", c: "👑", g: "Objects" },
  { n: "womans_hat", c: "👒", g: "Objects" },
  { n: "tophat", c: "🎩", g: "Objects" },
  { n: "mortar_board", c: "🎓", g: "Objects" },
  { n: "billed_cap", c: "🧢", g: "Objects" },
  { n: "military_helmet", c: "🪖", g: "Objects" },
  { n: "helmet_with_white_cross", c: "⛑️", g: "Objects" },
  { n: "prayer_beads", c: "📿", g: "Objects" },
  { n: "lipstick", c: "💄", g: "Objects" },
  { n: "ring", c: "💍", g: "Objects" },
  { n: "gem", c: "💎", g: "Objects" },
  { n: "mute", c: "🔇", g: "Objects" },
  { n: "speaker", c: "🔈", g: "Objects" },
  { n: "sound", c: "🔉", g: "Objects" },
  { n: "loud_sound", c: "🔊", g: "Objects" },
  { n: "loudspeaker", c: "📢", g: "Objects" },
  { n: "mega", c: "📣", g: "Objects" },
  { n: "postal_horn", c: "📯", g: "Objects" },
  { n: "bell", c: "🔔", g: "Objects" },
  { n: "no_bell", c: "🔕", g: "Objects" },
  { n: "musical_score", c: "🎼", g: "Objects" },
  { n: "musical_note", c: "🎵", g: "Objects" },
  { n: "notes", c: "🎶", g: "Objects" },
  { n: "studio_microphone", c: "🎙️", g: "Objects" },
  { n: "level_slider", c: "🎚️", g: "Objects" },
  { n: "control_knobs", c: "🎛️", g: "Objects" },
  { n: "microphone", c: "🎤", g: "Objects" },
  { n: "headphones", c: "🎧", g: "Objects" },
  { n: "radio", c: "📻", g: "Objects" },
  { n: "saxophone", c: "🎷", g: "Objects" },
  { n: "accordion", c: "🪗", g: "Objects" },
  { n: "guitar", c: "🎸", g: "Objects" },
  { n: "musical_keyboard", c: "🎹", g: "Objects" },
  { n: "trumpet", c: "🎺", g: "Objects" },
  { n: "violin", c: "🎻", g: "Objects" },
  { n: "banjo", c: "🪕", g: "Objects" },
  { n: "drum_with_drumsticks", c: "🥁", g: "Objects" },
  { n: "long_drum", c: "🪘", g: "Objects" },
  { n: "maracas", c: "🪇", g: "Objects" },
  { n: "flute", c: "🪈", g: "Objects" },
  { n: "harp", c: "🪉", g: "Objects" },
  { n: "iphone", c: "📱", g: "Objects" },
  { n: "calling", c: "📲", g: "Objects" },
  { n: "phone", c: "☎️", g: "Objects", a: ["telephone"] },
  { n: "telephone_receiver", c: "📞", g: "Objects" },
  { n: "pager", c: "📟", g: "Objects" },
  { n: "fax", c: "📠", g: "Objects" },
  { n: "battery", c: "🔋", g: "Objects" },
  { n: "low_battery", c: "🪫", g: "Objects" },
  { n: "electric_plug", c: "🔌", g: "Objects" },
  { n: "computer", c: "💻", g: "Objects" },
  { n: "desktop_computer", c: "🖥️", g: "Objects" },
  { n: "printer", c: "🖨️", g: "Objects" },
  { n: "keyboard", c: "⌨️", g: "Objects" },
  { n: "three_button_mouse", c: "🖱️", g: "Objects" },
  { n: "trackball", c: "🖲️", g: "Objects" },
  { n: "minidisc", c: "💽", g: "Objects" },
  { n: "floppy_disk", c: "💾", g: "Objects" },
  { n: "cd", c: "💿", g: "Objects" },
  { n: "dvd", c: "📀", g: "Objects" },
  { n: "abacus", c: "🧮", g: "Objects" },
  { n: "movie_camera", c: "🎥", g: "Objects" },
  { n: "film_frames", c: "🎞️", g: "Objects" },
  { n: "film_projector", c: "📽️", g: "Objects" },
  { n: "clapper", c: "🎬", g: "Objects" },
  { n: "tv", c: "📺", g: "Objects" },
  { n: "camera", c: "📷", g: "Objects" },
  { n: "camera_with_flash", c: "📸", g: "Objects" },
  { n: "video_camera", c: "📹", g: "Objects" },
  { n: "vhs", c: "📼", g: "Objects" },
  { n: "mag", c: "🔍", g: "Objects" },
  { n: "mag_right", c: "🔎", g: "Objects" },
  { n: "candle", c: "🕯️", g: "Objects" },
  { n: "bulb", c: "💡", g: "Objects" },
  { n: "flashlight", c: "🔦", g: "Objects" },
  { n: "izakaya_lantern", c: "🏮", g: "Objects", a: ["lantern"] },
  { n: "diya_lamp", c: "🪔", g: "Objects" },
  { n: "notebook_with_decorative_cover", c: "📔", g: "Objects" },
  { n: "closed_book", c: "📕", g: "Objects" },
  { n: "book", c: "📖", g: "Objects", a: ["open_book"] },
  { n: "green_book", c: "📗", g: "Objects" },
  { n: "blue_book", c: "📘", g: "Objects" },
  { n: "orange_book", c: "📙", g: "Objects" },
  { n: "books", c: "📚", g: "Objects" },
  { n: "notebook", c: "📓", g: "Objects" },
  { n: "ledger", c: "📒", g: "Objects" },
  { n: "page_with_curl", c: "📃", g: "Objects" },
  { n: "scroll", c: "📜", g: "Objects" },
  { n: "page_facing_up", c: "📄", g: "Objects" },
  { n: "newspaper", c: "📰", g: "Objects" },
  { n: "rolled_up_newspaper", c: "🗞️", g: "Objects" },
  { n: "bookmark_tabs", c: "📑", g: "Objects" },
  { n: "bookmark", c: "🔖", g: "Objects" },
  { n: "label", c: "🏷️", g: "Objects" },
  { n: "moneybag", c: "💰", g: "Objects" },
  { n: "coin", c: "🪙", g: "Objects" },
  { n: "yen", c: "💴", g: "Objects" },
  { n: "dollar", c: "💵", g: "Objects" },
  { n: "euro", c: "💶", g: "Objects" },
  { n: "pound", c: "💷", g: "Objects" },
  { n: "money_with_wings", c: "💸", g: "Objects" },
  { n: "credit_card", c: "💳", g: "Objects" },
  { n: "receipt", c: "🧾", g: "Objects" },
  { n: "chart", c: "💹", g: "Objects" },
  { n: "email", c: "✉️", g: "Objects", a: ["envelope"] },
  { n: "e-mail", c: "📧", g: "Objects" },
  { n: "incoming_envelope", c: "📨", g: "Objects" },
  { n: "envelope_with_arrow", c: "📩", g: "Objects" },
  { n: "outbox_tray", c: "📤", g: "Objects" },
  { n: "inbox_tray", c: "📥", g: "Objects" },
  { n: "package", c: "📦", g: "Objects" },
  { n: "mailbox", c: "📫", g: "Objects" },
  { n: "mailbox_closed", c: "📪", g: "Objects" },
  { n: "mailbox_with_mail", c: "📬", g: "Objects" },
  { n: "mailbox_with_no_mail", c: "📭", g: "Objects" },
  { n: "postbox", c: "📮", g: "Objects" },
  { n: "ballot_box_with_ballot", c: "🗳️", g: "Objects" },
  { n: "pencil2", c: "✏️", g: "Objects" },
  { n: "black_nib", c: "✒️", g: "Objects" },
  { n: "lower_left_fountain_pen", c: "🖋️", g: "Objects" },
  { n: "lower_left_ballpoint_pen", c: "🖊️", g: "Objects" },
  { n: "lower_left_paintbrush", c: "🖌️", g: "Objects" },
  { n: "lower_left_crayon", c: "🖍️", g: "Objects" },
  { n: "memo", c: "📝", g: "Objects", a: ["pencil"] },
  { n: "briefcase", c: "💼", g: "Objects" },
  { n: "file_folder", c: "📁", g: "Objects" },
  { n: "open_file_folder", c: "📂", g: "Objects" },
  { n: "card_index_dividers", c: "🗂️", g: "Objects" },
  { n: "date", c: "📅", g: "Objects" },
  { n: "calendar", c: "📆", g: "Objects" },
  { n: "spiral_note_pad", c: "🗒️", g: "Objects" },
  { n: "spiral_calendar_pad", c: "🗓️", g: "Objects" },
  { n: "card_index", c: "📇", g: "Objects" },
  { n: "chart_with_upwards_trend", c: "📈", g: "Objects" },
  { n: "chart_with_downwards_trend", c: "📉", g: "Objects" },
  { n: "bar_chart", c: "📊", g: "Objects" },
  { n: "clipboard", c: "📋", g: "Objects" },
  { n: "pushpin", c: "📌", g: "Objects" },
  { n: "round_pushpin", c: "📍", g: "Objects" },
  { n: "paperclip", c: "📎", g: "Objects" },
  { n: "linked_paperclips", c: "🖇️", g: "Objects" },
  { n: "straight_ruler", c: "📏", g: "Objects" },
  { n: "triangular_ruler", c: "📐", g: "Objects" },
  { n: "scissors", c: "✂️", g: "Objects" },
  { n: "card_file_box", c: "🗃️", g: "Objects" },
  { n: "file_cabinet", c: "🗄️", g: "Objects" },
  { n: "wastebasket", c: "🗑️", g: "Objects" },
  { n: "lock", c: "🔒", g: "Objects" },
  { n: "unlock", c: "🔓", g: "Objects" },
  { n: "lock_with_ink_pen", c: "🔏", g: "Objects" },
  { n: "closed_lock_with_key", c: "🔐", g: "Objects" },
  { n: "key", c: "🔑", g: "Objects" },
  { n: "old_key", c: "🗝️", g: "Objects" },
  { n: "hammer", c: "🔨", g: "Objects" },
  { n: "axe", c: "🪓", g: "Objects" },
  { n: "pick", c: "⛏️", g: "Objects" },
  { n: "hammer_and_pick", c: "⚒️", g: "Objects" },
  { n: "hammer_and_wrench", c: "🛠️", g: "Objects" },
  { n: "dagger_knife", c: "🗡️", g: "Objects" },
  { n: "crossed_swords", c: "⚔️", g: "Objects" },
  { n: "bomb", c: "💣", g: "Objects" },
  { n: "boomerang", c: "🪃", g: "Objects" },
  { n: "bow_and_arrow", c: "🏹", g: "Objects" },
  { n: "shield", c: "🛡️", g: "Objects" },
  { n: "carpentry_saw", c: "🪚", g: "Objects" },
  { n: "wrench", c: "🔧", g: "Objects" },
  { n: "screwdriver", c: "🪛", g: "Objects" },
  { n: "nut_and_bolt", c: "🔩", g: "Objects" },
  { n: "gear", c: "⚙️", g: "Objects" },
  { n: "compression", c: "🗜️", g: "Objects" },
  { n: "scales", c: "⚖️", g: "Objects" },
  { n: "probing_cane", c: "🦯", g: "Objects" },
  { n: "link", c: "🔗", g: "Objects" },
  { n: "broken_chain", c: "⛓️‍💥", g: "Objects" },
  { n: "chains", c: "⛓️", g: "Objects" },
  { n: "hook", c: "🪝", g: "Objects" },
  { n: "toolbox", c: "🧰", g: "Objects" },
  { n: "magnet", c: "🧲", g: "Objects" },
  { n: "ladder", c: "🪜", g: "Objects" },
  { n: "shovel", c: "🪏", g: "Objects" },
  { n: "alembic", c: "⚗️", g: "Objects" },
  { n: "test_tube", c: "🧪", g: "Objects" },
  { n: "petri_dish", c: "🧫", g: "Objects" },
  { n: "dna", c: "🧬", g: "Objects" },
  { n: "microscope", c: "🔬", g: "Objects" },
  { n: "telescope", c: "🔭", g: "Objects" },
  { n: "satellite_antenna", c: "📡", g: "Objects" },
  { n: "syringe", c: "💉", g: "Objects" },
  { n: "drop_of_blood", c: "🩸", g: "Objects" },
  { n: "pill", c: "💊", g: "Objects" },
  { n: "adhesive_bandage", c: "🩹", g: "Objects" },
  { n: "crutch", c: "🩼", g: "Objects" },
  { n: "stethoscope", c: "🩺", g: "Objects" },
  { n: "x-ray", c: "🩻", g: "Objects" },
  { n: "door", c: "🚪", g: "Objects" },
  { n: "elevator", c: "🛗", g: "Objects" },
  { n: "mirror", c: "🪞", g: "Objects" },
  { n: "window", c: "🪟", g: "Objects" },
  { n: "bed", c: "🛏️", g: "Objects" },
  { n: "couch_and_lamp", c: "🛋️", g: "Objects" },
  { n: "chair", c: "🪑", g: "Objects" },
  { n: "toilet", c: "🚽", g: "Objects" },
  { n: "plunger", c: "🪠", g: "Objects" },
  { n: "shower", c: "🚿", g: "Objects" },
  { n: "bathtub", c: "🛁", g: "Objects" },
  { n: "mouse_trap", c: "🪤", g: "Objects" },
  { n: "razor", c: "🪒", g: "Objects" },
  { n: "lotion_bottle", c: "🧴", g: "Objects" },
  { n: "safety_pin", c: "🧷", g: "Objects" },
  { n: "broom", c: "🧹", g: "Objects" },
  { n: "basket", c: "🧺", g: "Objects" },
  { n: "roll_of_paper", c: "🧻", g: "Objects" },
  { n: "bucket", c: "🪣", g: "Objects" },
  { n: "soap", c: "🧼", g: "Objects" },
  { n: "bubbles", c: "🫧", g: "Objects" },
  { n: "toothbrush", c: "🪥", g: "Objects" },
  { n: "sponge", c: "🧽", g: "Objects" },
  { n: "fire_extinguisher", c: "🧯", g: "Objects" },
  { n: "shopping_trolley", c: "🛒", g: "Objects" },
  { n: "smoking", c: "🚬", g: "Objects" },
  { n: "coffin", c: "⚰️", g: "Objects" },
  { n: "headstone", c: "🪦", g: "Objects" },
  { n: "funeral_urn", c: "⚱️", g: "Objects" },
  { n: "nazar_amulet", c: "🧿", g: "Objects" },
  { n: "hamsa", c: "🪬", g: "Objects" },
  { n: "moyai", c: "🗿", g: "Objects" },
  { n: "placard", c: "🪧", g: "Objects" },
  { n: "identification_card", c: "🪪", g: "Objects" },
  { n: "atm", c: "🏧", g: "Symbols" },
  { n: "put_litter_in_its_place", c: "🚮", g: "Symbols" },
  { n: "potable_water", c: "🚰", g: "Symbols" },
  { n: "wheelchair", c: "♿", g: "Symbols" },
  { n: "mens", c: "🚹", g: "Symbols" },
  { n: "womens", c: "🚺", g: "Symbols" },
  { n: "restroom", c: "🚻", g: "Symbols" },
  { n: "baby_symbol", c: "🚼", g: "Symbols" },
  { n: "passport_control", c: "🛂", g: "Symbols" },
  { n: "customs", c: "🛃", g: "Symbols" },
  { n: "baggage_claim", c: "🛄", g: "Symbols" },
  { n: "left_luggage", c: "🛅", g: "Symbols" },
  { n: "warning", c: "⚠️", g: "Symbols" },
  { n: "children_crossing", c: "🚸", g: "Symbols" },
  { n: "no_entry", c: "⛔", g: "Symbols" },
  { n: "no_entry_sign", c: "🚫", g: "Symbols" },
  { n: "no_bicycles", c: "🚳", g: "Symbols" },
  { n: "no_smoking", c: "🚭", g: "Symbols" },
  { n: "do_not_litter", c: "🚯", g: "Symbols" },
  { n: "non-potable_water", c: "🚱", g: "Symbols" },
  { n: "no_pedestrians", c: "🚷", g: "Symbols" },
  { n: "no_mobile_phones", c: "📵", g: "Symbols" },
  { n: "underage", c: "🔞", g: "Symbols" },
  { n: "radioactive_sign", c: "☢️", g: "Symbols" },
  { n: "biohazard_sign", c: "☣️", g: "Symbols" },
  { n: "arrow_up", c: "⬆️", g: "Symbols" },
  { n: "arrow_upper_right", c: "↗️", g: "Symbols" },
  { n: "arrow_right", c: "➡️", g: "Symbols" },
  { n: "arrow_lower_right", c: "↘️", g: "Symbols" },
  { n: "arrow_down", c: "⬇️", g: "Symbols" },
  { n: "arrow_lower_left", c: "↙️", g: "Symbols" },
  { n: "arrow_left", c: "⬅️", g: "Symbols" },
  { n: "arrow_upper_left", c: "↖️", g: "Symbols" },
  { n: "arrow_up_down", c: "↕️", g: "Symbols" },
  { n: "left_right_arrow", c: "↔️", g: "Symbols" },
  { n: "leftwards_arrow_with_hook", c: "↩️", g: "Symbols" },
  { n: "arrow_right_hook", c: "↪️", g: "Symbols" },
  { n: "arrow_heading_up", c: "⤴️", g: "Symbols" },
  { n: "arrow_heading_down", c: "⤵️", g: "Symbols" },
  { n: "arrows_clockwise", c: "🔃", g: "Symbols" },
  { n: "arrows_counterclockwise", c: "🔄", g: "Symbols" },
  { n: "back", c: "🔙", g: "Symbols" },
  { n: "end", c: "🔚", g: "Symbols" },
  { n: "on", c: "🔛", g: "Symbols" },
  { n: "soon", c: "🔜", g: "Symbols" },
  { n: "top", c: "🔝", g: "Symbols" },
  { n: "place_of_worship", c: "🛐", g: "Symbols" },
  { n: "atom_symbol", c: "⚛️", g: "Symbols" },
  { n: "om_symbol", c: "🕉️", g: "Symbols" },
  { n: "star_of_david", c: "✡️", g: "Symbols" },
  { n: "wheel_of_dharma", c: "☸️", g: "Symbols" },
  { n: "yin_yang", c: "☯️", g: "Symbols" },
  { n: "latin_cross", c: "✝️", g: "Symbols" },
  { n: "orthodox_cross", c: "☦️", g: "Symbols" },
  { n: "star_and_crescent", c: "☪️", g: "Symbols" },
  { n: "peace_symbol", c: "☮️", g: "Symbols" },
  { n: "menorah_with_nine_branches", c: "🕎", g: "Symbols" },
  { n: "six_pointed_star", c: "🔯", g: "Symbols" },
  { n: "khanda", c: "🪯", g: "Symbols" },
  { n: "aries", c: "♈", g: "Symbols" },
  { n: "taurus", c: "♉", g: "Symbols" },
  { n: "gemini", c: "♊", g: "Symbols" },
  { n: "cancer", c: "♋", g: "Symbols" },
  { n: "leo", c: "♌", g: "Symbols" },
  { n: "virgo", c: "♍", g: "Symbols" },
  { n: "libra", c: "♎", g: "Symbols" },
  { n: "scorpius", c: "♏", g: "Symbols" },
  { n: "sagittarius", c: "♐", g: "Symbols" },
  { n: "capricorn", c: "♑", g: "Symbols" },
  { n: "aquarius", c: "♒", g: "Symbols" },
  { n: "pisces", c: "♓", g: "Symbols" },
  { n: "ophiuchus", c: "⛎", g: "Symbols" },
  { n: "twisted_rightwards_arrows", c: "🔀", g: "Symbols" },
  { n: "repeat", c: "🔁", g: "Symbols" },
  { n: "repeat_one", c: "🔂", g: "Symbols" },
  { n: "arrow_forward", c: "▶️", g: "Symbols" },
  { n: "fast_forward", c: "⏩", g: "Symbols" },
  { n: "black_right_pointing_double_triangle_with_vertical_bar", c: "⏭️", g: "Symbols" },
  { n: "black_right_pointing_triangle_with_double_vertical_bar", c: "⏯️", g: "Symbols" },
  { n: "arrow_backward", c: "◀️", g: "Symbols" },
  { n: "rewind", c: "⏪", g: "Symbols" },
  { n: "black_left_pointing_double_triangle_with_vertical_bar", c: "⏮️", g: "Symbols" },
  { n: "arrow_up_small", c: "🔼", g: "Symbols" },
  { n: "arrow_double_up", c: "⏫", g: "Symbols" },
  { n: "arrow_down_small", c: "🔽", g: "Symbols" },
  { n: "arrow_double_down", c: "⏬", g: "Symbols" },
  { n: "double_vertical_bar", c: "⏸️", g: "Symbols" },
  { n: "black_square_for_stop", c: "⏹️", g: "Symbols" },
  { n: "black_circle_for_record", c: "⏺️", g: "Symbols" },
  { n: "eject", c: "⏏️", g: "Symbols" },
  { n: "cinema", c: "🎦", g: "Symbols" },
  { n: "low_brightness", c: "🔅", g: "Symbols" },
  { n: "high_brightness", c: "🔆", g: "Symbols" },
  { n: "signal_strength", c: "📶", g: "Symbols" },
  { n: "wireless", c: "🛜", g: "Symbols" },
  { n: "vibration_mode", c: "📳", g: "Symbols" },
  { n: "mobile_phone_off", c: "📴", g: "Symbols" },
  { n: "female_sign", c: "♀️", g: "Symbols" },
  { n: "male_sign", c: "♂️", g: "Symbols" },
  { n: "transgender_symbol", c: "⚧️", g: "Symbols" },
  { n: "heavy_multiplication_x", c: "✖️", g: "Symbols" },
  { n: "heavy_plus_sign", c: "➕", g: "Symbols" },
  { n: "heavy_minus_sign", c: "➖", g: "Symbols" },
  { n: "heavy_division_sign", c: "➗", g: "Symbols" },
  { n: "heavy_equals_sign", c: "🟰", g: "Symbols" },
  { n: "infinity", c: "♾️", g: "Symbols" },
  { n: "bangbang", c: "‼️", g: "Symbols" },
  { n: "interrobang", c: "⁉️", g: "Symbols" },
  { n: "question", c: "❓", g: "Symbols" },
  { n: "grey_question", c: "❔", g: "Symbols" },
  { n: "grey_exclamation", c: "❕", g: "Symbols" },
  { n: "exclamation", c: "❗", g: "Symbols", a: ["heavy_exclamation_mark"] },
  { n: "wavy_dash", c: "〰️", g: "Symbols" },
  { n: "currency_exchange", c: "💱", g: "Symbols" },
  { n: "heavy_dollar_sign", c: "💲", g: "Symbols" },
  { n: "medical_symbol", c: "⚕️", g: "Symbols", a: ["staff_of_aesculapius"] },
  { n: "recycle", c: "♻️", g: "Symbols" },
  { n: "fleur_de_lis", c: "⚜️", g: "Symbols" },
  { n: "trident", c: "🔱", g: "Symbols" },
  { n: "name_badge", c: "📛", g: "Symbols" },
  { n: "beginner", c: "🔰", g: "Symbols" },
  { n: "o", c: "⭕", g: "Symbols" },
  { n: "white_check_mark", c: "✅", g: "Symbols" },
  { n: "ballot_box_with_check", c: "☑️", g: "Symbols" },
  { n: "heavy_check_mark", c: "✔️", g: "Symbols" },
  { n: "x", c: "❌", g: "Symbols" },
  { n: "negative_squared_cross_mark", c: "❎", g: "Symbols" },
  { n: "curly_loop", c: "➰", g: "Symbols" },
  { n: "loop", c: "➿", g: "Symbols" },
  { n: "part_alternation_mark", c: "〽️", g: "Symbols" },
  { n: "eight_spoked_asterisk", c: "✳️", g: "Symbols" },
  { n: "eight_pointed_black_star", c: "✴️", g: "Symbols" },
  { n: "sparkle", c: "❇️", g: "Symbols" },
  { n: "copyright", c: "©️", g: "Symbols" },
  { n: "registered", c: "®️", g: "Symbols" },
  { n: "tm", c: "™️", g: "Symbols" },
  { n: "splatter", c: "🫟", g: "Symbols" },
  { n: "hash", c: "#️⃣", g: "Symbols" },
  { n: "keycap_star", c: "*️⃣", g: "Symbols" },
  { n: "zero", c: "0️⃣", g: "Symbols" },
  { n: "one", c: "1️⃣", g: "Symbols" },
  { n: "two", c: "2️⃣", g: "Symbols" },
  { n: "three", c: "3️⃣", g: "Symbols" },
  { n: "four", c: "4️⃣", g: "Symbols" },
  { n: "five", c: "5️⃣", g: "Symbols" },
  { n: "six", c: "6️⃣", g: "Symbols" },
  { n: "seven", c: "7️⃣", g: "Symbols" },
  { n: "eight", c: "8️⃣", g: "Symbols" },
  { n: "nine", c: "9️⃣", g: "Symbols" },
  { n: "keycap_ten", c: "🔟", g: "Symbols" },
  { n: "capital_abcd", c: "🔠", g: "Symbols" },
  { n: "abcd", c: "🔡", g: "Symbols" },
  { n: "1234", c: "🔢", g: "Symbols" },
  { n: "symbols", c: "🔣", g: "Symbols" },
  { n: "abc", c: "🔤", g: "Symbols" },
  { n: "a", c: "🅰️", g: "Symbols" },
  { n: "ab", c: "🆎", g: "Symbols" },
  { n: "b", c: "🅱️", g: "Symbols" },
  { n: "cl", c: "🆑", g: "Symbols" },
  { n: "cool", c: "🆒", g: "Symbols" },
  { n: "free", c: "🆓", g: "Symbols" },
  { n: "information_source", c: "ℹ️", g: "Symbols" },
  { n: "id", c: "🆔", g: "Symbols" },
  { n: "m", c: "Ⓜ️", g: "Symbols" },
  { n: "new", c: "🆕", g: "Symbols" },
  { n: "ng", c: "🆖", g: "Symbols" },
  { n: "o2", c: "🅾️", g: "Symbols" },
  { n: "ok", c: "🆗", g: "Symbols" },
  { n: "parking", c: "🅿️", g: "Symbols" },
  { n: "sos", c: "🆘", g: "Symbols" },
  { n: "up", c: "🆙", g: "Symbols" },
  { n: "vs", c: "🆚", g: "Symbols" },
  { n: "koko", c: "🈁", g: "Symbols" },
  { n: "sa", c: "🈂️", g: "Symbols" },
  { n: "u6708", c: "🈷️", g: "Symbols" },
  { n: "u6709", c: "🈶", g: "Symbols" },
  { n: "u6307", c: "🈯", g: "Symbols" },
  { n: "ideograph_advantage", c: "🉐", g: "Symbols" },
  { n: "u5272", c: "🈹", g: "Symbols" },
  { n: "u7121", c: "🈚", g: "Symbols" },
  { n: "u7981", c: "🈲", g: "Symbols" },
  { n: "accept", c: "🉑", g: "Symbols" },
  { n: "u7533", c: "🈸", g: "Symbols" },
  { n: "u5408", c: "🈴", g: "Symbols" },
  { n: "u7a7a", c: "🈳", g: "Symbols" },
  { n: "congratulations", c: "㊗️", g: "Symbols" },
  { n: "secret", c: "㊙️", g: "Symbols" },
  { n: "u55b6", c: "🈺", g: "Symbols" },
  { n: "u6e80", c: "🈵", g: "Symbols" },
  { n: "red_circle", c: "🔴", g: "Symbols" },
  { n: "large_orange_circle", c: "🟠", g: "Symbols" },
  { n: "large_yellow_circle", c: "🟡", g: "Symbols" },
  { n: "large_green_circle", c: "🟢", g: "Symbols" },
  { n: "large_blue_circle", c: "🔵", g: "Symbols" },
  { n: "large_purple_circle", c: "🟣", g: "Symbols" },
  { n: "large_brown_circle", c: "🟤", g: "Symbols" },
  { n: "black_circle", c: "⚫", g: "Symbols" },
  { n: "white_circle", c: "⚪", g: "Symbols" },
  { n: "large_red_square", c: "🟥", g: "Symbols" },
  { n: "large_orange_square", c: "🟧", g: "Symbols" },
  { n: "large_yellow_square", c: "🟨", g: "Symbols" },
  { n: "large_green_square", c: "🟩", g: "Symbols" },
  { n: "large_blue_square", c: "🟦", g: "Symbols" },
  { n: "large_purple_square", c: "🟪", g: "Symbols" },
  { n: "large_brown_square", c: "🟫", g: "Symbols" },
  { n: "black_large_square", c: "⬛", g: "Symbols" },
  { n: "white_large_square", c: "⬜", g: "Symbols" },
  { n: "black_medium_square", c: "◼️", g: "Symbols" },
  { n: "white_medium_square", c: "◻️", g: "Symbols" },
  { n: "black_medium_small_square", c: "◾", g: "Symbols" },
  { n: "white_medium_small_square", c: "◽", g: "Symbols" },
  { n: "black_small_square", c: "▪️", g: "Symbols" },
  { n: "white_small_square", c: "▫️", g: "Symbols" },
  { n: "large_orange_diamond", c: "🔶", g: "Symbols" },
  { n: "large_blue_diamond", c: "🔷", g: "Symbols" },
  { n: "small_orange_diamond", c: "🔸", g: "Symbols" },
  { n: "small_blue_diamond", c: "🔹", g: "Symbols" },
  { n: "small_red_triangle", c: "🔺", g: "Symbols" },
  { n: "small_red_triangle_down", c: "🔻", g: "Symbols" },
  { n: "diamond_shape_with_a_dot_inside", c: "💠", g: "Symbols" },
  { n: "radio_button", c: "🔘", g: "Symbols" },
  { n: "white_square_button", c: "🔳", g: "Symbols" },
  { n: "black_square_button", c: "🔲", g: "Symbols" },
  { n: "checkered_flag", c: "🏁", g: "Flags" },
  { n: "triangular_flag_on_post", c: "🚩", g: "Flags" },
  { n: "crossed_flags", c: "🎌", g: "Flags" },
  { n: "waving_black_flag", c: "🏴", g: "Flags" },
  { n: "waving_white_flag", c: "🏳️", g: "Flags" },
  { n: "rainbow-flag", c: "🏳️‍🌈", g: "Flags" },
  { n: "transgender_flag", c: "🏳️‍⚧️", g: "Flags" },
  { n: "pirate_flag", c: "🏴‍☠️", g: "Flags" },
  { n: "flag-ac", c: "🇦🇨", g: "Flags" },
  { n: "flag-ad", c: "🇦🇩", g: "Flags" },
  { n: "flag-ae", c: "🇦🇪", g: "Flags" },
  { n: "flag-af", c: "🇦🇫", g: "Flags" },
  { n: "flag-ag", c: "🇦🇬", g: "Flags" },
  { n: "flag-ai", c: "🇦🇮", g: "Flags" },
  { n: "flag-al", c: "🇦🇱", g: "Flags" },
  { n: "flag-am", c: "🇦🇲", g: "Flags" },
  { n: "flag-ao", c: "🇦🇴", g: "Flags" },
  { n: "flag-aq", c: "🇦🇶", g: "Flags" },
  { n: "flag-ar", c: "🇦🇷", g: "Flags" },
  { n: "flag-as", c: "🇦🇸", g: "Flags" },
  { n: "flag-at", c: "🇦🇹", g: "Flags" },
  { n: "flag-au", c: "🇦🇺", g: "Flags" },
  { n: "flag-aw", c: "🇦🇼", g: "Flags" },
  { n: "flag-ax", c: "🇦🇽", g: "Flags" },
  { n: "flag-az", c: "🇦🇿", g: "Flags" },
  { n: "flag-ba", c: "🇧🇦", g: "Flags" },
  { n: "flag-bb", c: "🇧🇧", g: "Flags" },
  { n: "flag-bd", c: "🇧🇩", g: "Flags" },
  { n: "flag-be", c: "🇧🇪", g: "Flags" },
  { n: "flag-bf", c: "🇧🇫", g: "Flags" },
  { n: "flag-bg", c: "🇧🇬", g: "Flags" },
  { n: "flag-bh", c: "🇧🇭", g: "Flags" },
  { n: "flag-bi", c: "🇧🇮", g: "Flags" },
  { n: "flag-bj", c: "🇧🇯", g: "Flags" },
  { n: "flag-bl", c: "🇧🇱", g: "Flags" },
  { n: "flag-bm", c: "🇧🇲", g: "Flags" },
  { n: "flag-bn", c: "🇧🇳", g: "Flags" },
  { n: "flag-bo", c: "🇧🇴", g: "Flags" },
  { n: "flag-bq", c: "🇧🇶", g: "Flags" },
  { n: "flag-br", c: "🇧🇷", g: "Flags" },
  { n: "flag-bs", c: "🇧🇸", g: "Flags" },
  { n: "flag-bt", c: "🇧🇹", g: "Flags" },
  { n: "flag-bv", c: "🇧🇻", g: "Flags" },
  { n: "flag-bw", c: "🇧🇼", g: "Flags" },
  { n: "flag-by", c: "🇧🇾", g: "Flags" },
  { n: "flag-bz", c: "🇧🇿", g: "Flags" },
  { n: "flag-ca", c: "🇨🇦", g: "Flags" },
  { n: "flag-cc", c: "🇨🇨", g: "Flags" },
  { n: "flag-cd", c: "🇨🇩", g: "Flags" },
  { n: "flag-cf", c: "🇨🇫", g: "Flags" },
  { n: "flag-cg", c: "🇨🇬", g: "Flags" },
  { n: "flag-ch", c: "🇨🇭", g: "Flags" },
  { n: "flag-ci", c: "🇨🇮", g: "Flags" },
  { n: "flag-ck", c: "🇨🇰", g: "Flags" },
  { n: "flag-cl", c: "🇨🇱", g: "Flags" },
  { n: "flag-cm", c: "🇨🇲", g: "Flags" },
  { n: "cn", c: "🇨🇳", g: "Flags", a: ["flag-cn"] },
  { n: "flag-co", c: "🇨🇴", g: "Flags" },
  { n: "flag-cp", c: "🇨🇵", g: "Flags" },
  { n: "flag-sark", c: "🇨🇶", g: "Flags" },
  { n: "flag-cr", c: "🇨🇷", g: "Flags" },
  { n: "flag-cu", c: "🇨🇺", g: "Flags" },
  { n: "flag-cv", c: "🇨🇻", g: "Flags" },
  { n: "flag-cw", c: "🇨🇼", g: "Flags" },
  { n: "flag-cx", c: "🇨🇽", g: "Flags" },
  { n: "flag-cy", c: "🇨🇾", g: "Flags" },
  { n: "flag-cz", c: "🇨🇿", g: "Flags" },
  { n: "de", c: "🇩🇪", g: "Flags", a: ["flag-de"] },
  { n: "flag-dg", c: "🇩🇬", g: "Flags" },
  { n: "flag-dj", c: "🇩🇯", g: "Flags" },
  { n: "flag-dk", c: "🇩🇰", g: "Flags" },
  { n: "flag-dm", c: "🇩🇲", g: "Flags" },
  { n: "flag-do", c: "🇩🇴", g: "Flags" },
  { n: "flag-dz", c: "🇩🇿", g: "Flags" },
  { n: "flag-ea", c: "🇪🇦", g: "Flags" },
  { n: "flag-ec", c: "🇪🇨", g: "Flags" },
  { n: "flag-ee", c: "🇪🇪", g: "Flags" },
  { n: "flag-eg", c: "🇪🇬", g: "Flags" },
  { n: "flag-eh", c: "🇪🇭", g: "Flags" },
  { n: "flag-er", c: "🇪🇷", g: "Flags" },
  { n: "es", c: "🇪🇸", g: "Flags", a: ["flag-es"] },
  { n: "flag-et", c: "🇪🇹", g: "Flags" },
  { n: "flag-eu", c: "🇪🇺", g: "Flags" },
  { n: "flag-fi", c: "🇫🇮", g: "Flags" },
  { n: "flag-fj", c: "🇫🇯", g: "Flags" },
  { n: "flag-fk", c: "🇫🇰", g: "Flags" },
  { n: "flag-fm", c: "🇫🇲", g: "Flags" },
  { n: "flag-fo", c: "🇫🇴", g: "Flags" },
  { n: "fr", c: "🇫🇷", g: "Flags", a: ["flag-fr"] },
  { n: "flag-ga", c: "🇬🇦", g: "Flags" },
  { n: "gb", c: "🇬🇧", g: "Flags", a: ["uk", "flag-gb"] },
  { n: "flag-gd", c: "🇬🇩", g: "Flags" },
  { n: "flag-ge", c: "🇬🇪", g: "Flags" },
  { n: "flag-gf", c: "🇬🇫", g: "Flags" },
  { n: "flag-gg", c: "🇬🇬", g: "Flags" },
  { n: "flag-gh", c: "🇬🇭", g: "Flags" },
  { n: "flag-gi", c: "🇬🇮", g: "Flags" },
  { n: "flag-gl", c: "🇬🇱", g: "Flags" },
  { n: "flag-gm", c: "🇬🇲", g: "Flags" },
  { n: "flag-gn", c: "🇬🇳", g: "Flags" },
  { n: "flag-gp", c: "🇬🇵", g: "Flags" },
  { n: "flag-gq", c: "🇬🇶", g: "Flags" },
  { n: "flag-gr", c: "🇬🇷", g: "Flags" },
  { n: "flag-gs", c: "🇬🇸", g: "Flags" },
  { n: "flag-gt", c: "🇬🇹", g: "Flags" },
  { n: "flag-gu", c: "🇬🇺", g: "Flags" },
  { n: "flag-gw", c: "🇬🇼", g: "Flags" },
  { n: "flag-gy", c: "🇬🇾", g: "Flags" },
  { n: "flag-hk", c: "🇭🇰", g: "Flags" },
  { n: "flag-hm", c: "🇭🇲", g: "Flags" },
  { n: "flag-hn", c: "🇭🇳", g: "Flags" },
  { n: "flag-hr", c: "🇭🇷", g: "Flags" },
  { n: "flag-ht", c: "🇭🇹", g: "Flags" },
  { n: "flag-hu", c: "🇭🇺", g: "Flags" },
  { n: "flag-ic", c: "🇮🇨", g: "Flags" },
  { n: "flag-id", c: "🇮🇩", g: "Flags" },
  { n: "flag-ie", c: "🇮🇪", g: "Flags" },
  { n: "flag-il", c: "🇮🇱", g: "Flags" },
  { n: "flag-im", c: "🇮🇲", g: "Flags" },
  { n: "flag-in", c: "🇮🇳", g: "Flags" },
  { n: "flag-io", c: "🇮🇴", g: "Flags" },
  { n: "flag-iq", c: "🇮🇶", g: "Flags" },
  { n: "flag-ir", c: "🇮🇷", g: "Flags" },
  { n: "flag-is", c: "🇮🇸", g: "Flags" },
  { n: "it", c: "🇮🇹", g: "Flags", a: ["flag-it"] },
  { n: "flag-je", c: "🇯🇪", g: "Flags" },
  { n: "flag-jm", c: "🇯🇲", g: "Flags" },
  { n: "flag-jo", c: "🇯🇴", g: "Flags" },
  { n: "jp", c: "🇯🇵", g: "Flags", a: ["flag-jp"] },
  { n: "flag-ke", c: "🇰🇪", g: "Flags" },
  { n: "flag-kg", c: "🇰🇬", g: "Flags" },
  { n: "flag-kh", c: "🇰🇭", g: "Flags" },
  { n: "flag-ki", c: "🇰🇮", g: "Flags" },
  { n: "flag-km", c: "🇰🇲", g: "Flags" },
  { n: "flag-kn", c: "🇰🇳", g: "Flags" },
  { n: "flag-kp", c: "🇰🇵", g: "Flags" },
  { n: "kr", c: "🇰🇷", g: "Flags", a: ["flag-kr"] },
  { n: "flag-kw", c: "🇰🇼", g: "Flags" },
  { n: "flag-ky", c: "🇰🇾", g: "Flags" },
  { n: "flag-kz", c: "🇰🇿", g: "Flags" },
  { n: "flag-la", c: "🇱🇦", g: "Flags" },
  { n: "flag-lb", c: "🇱🇧", g: "Flags" },
  { n: "flag-lc", c: "🇱🇨", g: "Flags" },
  { n: "flag-li", c: "🇱🇮", g: "Flags" },
  { n: "flag-lk", c: "🇱🇰", g: "Flags" },
  { n: "flag-lr", c: "🇱🇷", g: "Flags" },
  { n: "flag-ls", c: "🇱🇸", g: "Flags" },
  { n: "flag-lt", c: "🇱🇹", g: "Flags" },
  { n: "flag-lu", c: "🇱🇺", g: "Flags" },
  { n: "flag-lv", c: "🇱🇻", g: "Flags" },
  { n: "flag-ly", c: "🇱🇾", g: "Flags" },
  { n: "flag-ma", c: "🇲🇦", g: "Flags" },
  { n: "flag-mc", c: "🇲🇨", g: "Flags" },
  { n: "flag-md", c: "🇲🇩", g: "Flags" },
  { n: "flag-me", c: "🇲🇪", g: "Flags" },
  { n: "flag-mf", c: "🇲🇫", g: "Flags" },
  { n: "flag-mg", c: "🇲🇬", g: "Flags" },
  { n: "flag-mh", c: "🇲🇭", g: "Flags" },
  { n: "flag-mk", c: "🇲🇰", g: "Flags" },
  { n: "flag-ml", c: "🇲🇱", g: "Flags" },
  { n: "flag-mm", c: "🇲🇲", g: "Flags" },
  { n: "flag-mn", c: "🇲🇳", g: "Flags" },
  { n: "flag-mo", c: "🇲🇴", g: "Flags" },
  { n: "flag-mp", c: "🇲🇵", g: "Flags" },
  { n: "flag-mq", c: "🇲🇶", g: "Flags" },
  { n: "flag-mr", c: "🇲🇷", g: "Flags" },
  { n: "flag-ms", c: "🇲🇸", g: "Flags" },
  { n: "flag-mt", c: "🇲🇹", g: "Flags" },
  { n: "flag-mu", c: "🇲🇺", g: "Flags" },
  { n: "flag-mv", c: "🇲🇻", g: "Flags" },
  { n: "flag-mw", c: "🇲🇼", g: "Flags" },
  { n: "flag-mx", c: "🇲🇽", g: "Flags" },
  { n: "flag-my", c: "🇲🇾", g: "Flags" },
  { n: "flag-mz", c: "🇲🇿", g: "Flags" },
  { n: "flag-na", c: "🇳🇦", g: "Flags" },
  { n: "flag-nc", c: "🇳🇨", g: "Flags" },
  { n: "flag-ne", c: "🇳🇪", g: "Flags" },
  { n: "flag-nf", c: "🇳🇫", g: "Flags" },
  { n: "flag-ng", c: "🇳🇬", g: "Flags" },
  { n: "flag-ni", c: "🇳🇮", g: "Flags" },
  { n: "flag-nl", c: "🇳🇱", g: "Flags" },
  { n: "flag-no", c: "🇳🇴", g: "Flags" },
  { n: "flag-np", c: "🇳🇵", g: "Flags" },
  { n: "flag-nr", c: "🇳🇷", g: "Flags" },
  { n: "flag-nu", c: "🇳🇺", g: "Flags" },
  { n: "flag-nz", c: "🇳🇿", g: "Flags" },
  { n: "flag-om", c: "🇴🇲", g: "Flags" },
  { n: "flag-pa", c: "🇵🇦", g: "Flags" },
  { n: "flag-pe", c: "🇵🇪", g: "Flags" },
  { n: "flag-pf", c: "🇵🇫", g: "Flags" },
  { n: "flag-pg", c: "🇵🇬", g: "Flags" },
  { n: "flag-ph", c: "🇵🇭", g: "Flags" },
  { n: "flag-pk", c: "🇵🇰", g: "Flags" },
  { n: "flag-pl", c: "🇵🇱", g: "Flags" },
  { n: "flag-pm", c: "🇵🇲", g: "Flags" },
  { n: "flag-pn", c: "🇵🇳", g: "Flags" },
  { n: "flag-pr", c: "🇵🇷", g: "Flags" },
  { n: "flag-ps", c: "🇵🇸", g: "Flags" },
  { n: "flag-pt", c: "🇵🇹", g: "Flags" },
  { n: "flag-pw", c: "🇵🇼", g: "Flags" },
  { n: "flag-py", c: "🇵🇾", g: "Flags" },
  { n: "flag-qa", c: "🇶🇦", g: "Flags" },
  { n: "flag-re", c: "🇷🇪", g: "Flags" },
  { n: "flag-ro", c: "🇷🇴", g: "Flags" },
  { n: "flag-rs", c: "🇷🇸", g: "Flags" },
  { n: "ru", c: "🇷🇺", g: "Flags", a: ["flag-ru"] },
  { n: "flag-rw", c: "🇷🇼", g: "Flags" },
  { n: "flag-sa", c: "🇸🇦", g: "Flags" },
  { n: "flag-sb", c: "🇸🇧", g: "Flags" },
  { n: "flag-sc", c: "🇸🇨", g: "Flags" },
  { n: "flag-sd", c: "🇸🇩", g: "Flags" },
  { n: "flag-se", c: "🇸🇪", g: "Flags" },
  { n: "flag-sg", c: "🇸🇬", g: "Flags" },
  { n: "flag-sh", c: "🇸🇭", g: "Flags" },
  { n: "flag-si", c: "🇸🇮", g: "Flags" },
  { n: "flag-sj", c: "🇸🇯", g: "Flags" },
  { n: "flag-sk", c: "🇸🇰", g: "Flags" },
  { n: "flag-sl", c: "🇸🇱", g: "Flags" },
  { n: "flag-sm", c: "🇸🇲", g: "Flags" },
  { n: "flag-sn", c: "🇸🇳", g: "Flags" },
  { n: "flag-so", c: "🇸🇴", g: "Flags" },
  { n: "flag-sr", c: "🇸🇷", g: "Flags" },
  { n: "flag-ss", c: "🇸🇸", g: "Flags" },
  { n: "flag-st", c: "🇸🇹", g: "Flags" },
  { n: "flag-sv", c: "🇸🇻", g: "Flags" },
  { n: "flag-sx", c: "🇸🇽", g: "Flags" },
  { n: "flag-sy", c: "🇸🇾", g: "Flags" },
  { n: "flag-sz", c: "🇸🇿", g: "Flags" },
  { n: "flag-ta", c: "🇹🇦", g: "Flags" },
  { n: "flag-tc", c: "🇹🇨", g: "Flags" },
  { n: "flag-td", c: "🇹🇩", g: "Flags" },
  { n: "flag-tf", c: "🇹🇫", g: "Flags" },
  { n: "flag-tg", c: "🇹🇬", g: "Flags" },
  { n: "flag-th", c: "🇹🇭", g: "Flags" },
  { n: "flag-tj", c: "🇹🇯", g: "Flags" },
  { n: "flag-tk", c: "🇹🇰", g: "Flags" },
  { n: "flag-tl", c: "🇹🇱", g: "Flags" },
  { n: "flag-tm", c: "🇹🇲", g: "Flags" },
  { n: "flag-tn", c: "🇹🇳", g: "Flags" },
  { n: "flag-to", c: "🇹🇴", g: "Flags" },
  { n: "flag-tr", c: "🇹🇷", g: "Flags" },
  { n: "flag-tt", c: "🇹🇹", g: "Flags" },
  { n: "flag-tv", c: "🇹🇻", g: "Flags" },
  { n: "flag-tw", c: "🇹🇼", g: "Flags" },
  { n: "flag-tz", c: "🇹🇿", g: "Flags" },
  { n: "flag-ua", c: "🇺🇦", g: "Flags" },
  { n: "flag-ug", c: "🇺🇬", g: "Flags" },
  { n: "flag-um", c: "🇺🇲", g: "Flags" },
  { n: "flag-un", c: "🇺🇳", g: "Flags" },
  { n: "us", c: "🇺🇸", g: "Flags", a: ["flag-us"] },
  { n: "flag-uy", c: "🇺🇾", g: "Flags" },
  { n: "flag-uz", c: "🇺🇿", g: "Flags" },
  { n: "flag-va", c: "🇻🇦", g: "Flags" },
  { n: "flag-vc", c: "🇻🇨", g: "Flags" },
  { n: "flag-ve", c: "🇻🇪", g: "Flags" },
  { n: "flag-vg", c: "🇻🇬", g: "Flags" },
  { n: "flag-vi", c: "🇻🇮", g: "Flags" },
  { n: "flag-vn", c: "🇻🇳", g: "Flags" },
  { n: "flag-vu", c: "🇻🇺", g: "Flags" },
  { n: "flag-wf", c: "🇼🇫", g: "Flags" },
  { n: "flag-ws", c: "🇼🇸", g: "Flags" },
  { n: "flag-xk", c: "🇽🇰", g: "Flags" },
  { n: "flag-ye", c: "🇾🇪", g: "Flags" },
  { n: "flag-yt", c: "🇾🇹", g: "Flags" },
  { n: "flag-za", c: "🇿🇦", g: "Flags" },
  { n: "flag-zm", c: "🇿🇲", g: "Flags" },
  { n: "flag-zw", c: "🇿🇼", g: "Flags" },
  { n: "flag-england", c: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", g: "Flags" },
  { n: "flag-scotland", c: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", g: "Flags" },
  { n: "flag-wales", c: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", g: "Flags" },
];
